### ISSUE TITLE
Enhance TestZkCallbackHandlerLeak

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1102]
testRemoveUserCbHandlerOnPathRemoval has a flaky test

Assert
        .assertEquals(watchPaths.get("existWatches").size(), 2,
            "Should have 2 exist-watches: CURRENTSTATE/{oldSessionId} and CURRENTSTATE/{oldSessionId}/TestDB0");

**Comment by jiajunwang** [comment]
More fixes have been checked in since this issue. The test should be stable. Close it for now.
If the error happens again, we have an auto issue creating mechanism to track.
