### ISSUE TITLE
SharedZkClientFactory retains reference to closed ZkConnectionManagers

### ISSUE THREAD

**Issue by narendly** [apache/helix#1126]
```
  // Close the ZkConnectionManager if no other shared client is referring to it.
  // Note the close operation of connection manager needs to be synchronized with the pool operation
  // to avoid race condition.
  private void cleanupConnectionManager(ZkConnectionManager zkConnectionManager) {
    synchronized (_connectionManagerPool) {
      zkConnectionManager.close(true);
    }
  }
```

Here, shouldn't we remove closed references?

Need to remove this ZkConnectionManager from connectionManagerPool.

**Comment by jiajunwang** [comment]
Yeah, it should be done.
Especially with more information added to the connection config, there might be more connections created and hold in the pool.

**Comment by narendly** [comment]
When shared zk client gets created, it adds itself as the watcher, so it will never fully close if skipIfWatched is set to true. Is that intended?

**Comment by jiajunwang** [comment]
> When shared zk client gets created, it adds itself as the watcher, so it will never fully close if skipIfWatched is set to true. Is that intended?

This shared zk client should be closed by the user's code (from the ZkClient module perspective) as well. Then the reference count will be zero. And the real connection will be closed.

**Comment by manick02** [comment]
If none has taken this issue, Can I look at this issue and submit a commit? This would help me understand helix better

**Comment by narendly** [comment]
@manick02 
Sure. If you want, you could submit a pull request with a commit and ask for a review.
