### ISSUE TITLE
TaskStateModelFactory leaks thousands of threads in the test.

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#1139]
The recent investigation of the test issues shows that the TaskStateModelFactories that are created in the tests are not properly cleaned up. The threadpool, as well as the running threads inside, is not closed. This occupies lots of resources.

**Comment by jiajunwang** [comment]
This work is also related to #1137.

We will just record the result here. The test can pass on macbook laptop now, due to less thread usage.

Before the fix:
![Screen Shot 2020-07-13 at 12 06 28 PM](https://user-images.githubusercontent.com/1803880/87343286-76faab80-c501-11ea-8b0f-330721a540f3.png)

After the fix:
![Screen Shot 2020-07-13 at 12 08 13 PM](https://user-images.githubusercontent.com/1803880/87343338-8e399900-c501-11ea-80c2-b81947ba4108.png)

**Comment by narendly** [comment]
@jiajunwang Very cool! Number of threads from 7.5k -> 2.3k.
