### ISSUE TITLE
Duplicate classes in exported jars

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#1198]
There are duplicate classes at runtime since 1.0+, because of multiple modules packaging. Two different JARs contain the same package but with different contents. Eg, both helix-core.jar and metrics-common.jar contains `SensorNameProvider.class`. And at tests runtime, we have a check to detect duplicate classes and this causes tests failure.

```
:application-war:treatyOfVersailles FAILED |  
-- | --
  | check war for conflicts within application.war
found 148 duplicates
--
found org/apache/helix/msdcommon/util/ZkValidationUtil.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar, WEB-INF/lib/metadata-store-directory-common-1.0.1.3.jar] |  
-- | --
  | found org/apache/helix/SystemPropertyKeys.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar] |  
  | found org/apache/helix/ZNRecord.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar] |  
  | found org/apache/helix/ZNRecordDelta.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar] |  
  | found org/apache/helix/zookeeper/api/client/ChildrenSubscribeResult.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar, WEB-INF/lib/zookeeper-api-1.0.1.3.jar] |  
  | found org/apache/helix/zookeeper/api/client/HelixZkClient$ZkClientConfig.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar, WEB-INF/lib/zookeeper-api-1.0.1.3.jar] |  
  | found org/apache/helix/zookeeper/api/client/HelixZkClient$ZkConnectionConfig.class inside [WEB-INF/lib/helix-core-1.0.1.3.jar, WEB-INF/lib/helix-common-1.0.1.3.jar, WEB-INF/lib/zookeeper-api-1.0.1.3.jar]
```

The problem is, when we package the helix jars, the dependent subproject's classes are packaged into helix-core.jar: all classes in module helix-core and its dependencies match `org.apache.helix.*` are packaged to helix-core.jar. Then there are duplicate classes from metrics-common.jar/zookeeper-api.jar/helix-core.jar

Though helix doesn't have duplicate classes in the same package, it is still not a good practice to package the same class into two different jars that have dependency relation.

It is necessary to clean up the duplicate classes. And small refactoring work is needed to fix this issue.

**Comment by narendly** [comment]
> There are duplicate classes at runtime since 1.0+, because of multiple modules packaging. Two different JARs contain the same package but with different contents. Eg, both helix-core.jar and metrics-common.jar contains `SensorNameProvider.class`. And at tests runtime, we have a check to detect duplicate classes and this causes tests failure.
> 
> The problem is, when we package the helix jars, the dependent subproject's classes are packaged into helix-core.jar: all classes in module helix-core and its dependencies match `org.apache.helix.*` are packaged to helix-core.jar. Then there are duplicate classes from metrics-common.jar/zookeeper-api.jar/helix-core.jar
> 
> Though helix doesn't have duplicate classes in the same package, it is still not a good practice to package the same class into two different jars that have dependency relation.
> 

I'm not understanding what kind of test failures we are seeing. Could you post what failures we are seeing here?
