### ISSUE TITLE
Identify and fix leaked threads of ClusterManager in our unit test

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1216]
There are cases of leaking ClusterManager and its subclasses. The leaked threads can be in hundreds, Note, relying on GC of the ClusterManager object does not mean the thread is shutdown. For example TestNoDoubleAssign.

**Comment by lei-xia** [comment]
Can we make this issue/description more clear here? i.e, this is to fix the leak of ClusterManager in our unit tests.  Otherwise, it could create confusion here that we may have thread leak issue in our HelixManager code.
