### ISSUE TITLE
Fix unstable test TestListenerCallback

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1233]
TestListenerCallback relies on sleep(500ms). This is the source of unstableness of this test. We should change it to Test.verify( lambda to validate,  'larger converative timeout value');

For example, here is one log:

[ERROR] testScopedConfigChangeListener(org.apache.helix.TestListenerCallback) Time elapsed: 1.149 s <<< FAILURE!
java.lang.AssertionError: Should get clusterConfig callback invoked since we change clusterConfig expected: but was:
at org.apache.helix.TestListenerCallback.testScopedConfigChangeListener(TestListenerCallback.java:231)

**Comment by kaisun2000** [comment]
#1227 address this issue.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
