### ISSUE TITLE
Investigate and fix flaky test TestWorkflowTimeout

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1234]
Log:

>[ERROR] testWorkflowPausedTimeout(org.apache.helix.integration.task.TestWorkflowTimeout) Time elapsed: 8,280.587 s <<< FAILURE!
org.apache.helix.HelixException: Workflow "testWorkflowPausedTimeout" context is empty or not in states: "[TIMED_OUT]", current state: "STOPPED"
at org.apache.helix.integration.task.TestWorkflowTimeout.testWorkflowPausedTimeout(TestWorkflowTimeout.java:81)

>START testJobQueueNotApplyTimeout at Fri Aug 07 09:04:11 PDT 2020
END testJobQueueNotApplyTimeout at Fri Aug 07 09:04:12 PDT 2020, took: 635ms.
START testWorkflowPausedTimeout at Fri Aug 07 09:04:12 PDT 2020
38797870 [Timer-2059] ERROR org.apache.helix.controller.GenericHelixController  - Time task failed. Rebalance task type: OnDemandRebalance, cluster: CLUSTER_TestTaskRebalancerStopResume
**org.apache.helix.HelixException: HelixManager (ZkClient) is not connected. Call HelixManager#connect()
        at org.apache.helix.manager.zk.ZKHelixManager.checkConnected(ZKHelixManager.java:387)
        at org.apache.helix.manager.zk.ZKHelixManager.getHelixDataAccessor(ZKHelixManager.java:658)
        at org.apache.helix.controller.GenericHelixController$RebalanceTask.run(GenericHelixController.java:288)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)**
END testWorkflowPausedTimeout at Fri Aug 07 11:22:12 PDT 2020, took: 8280583ms.
START testWorkflowRunningTime at Fri Aug 07 11:22:12 PDT 2020
END testWorkflowRunningTime at Fri Aug 07 11:22:14 PDT 2020, took: 1162ms.
START testWorkflowTimeoutWhenWorkflowCompleted at Fri Aug 07 11:22:14 PDT 2020
END testWorkflowTimeoutWhenWorkflowCompleted at Fri Aug 07 11:22:16 PDT 2020, took: 2078ms.
38801160 [HelixController-pipeline-task-CLUSTER_TestWorkflowTimeout-(472b9896_TASK)] ERROR org.apache.helix.task.WorkflowDispatcher  - Workflow context is not created for testWorkflowTimeoutWhenWorkflowCompleted. Workflow config is missing!
38801168 [HelixController-pipeline-default-CLUSTER_TestWorkflowTimeout-(afd55339_DEFAULT)] ERROR org.apache.helix.controller.GenericHelixController  - Exception while executing DEFAULT pipeline: CLUSTER_TestWorkflowTimeout for cluster [org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1683), org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1820), org.apache.helix.zookeeper.zkclient.ZkClient.readData(ZkClient.java:1812), org.apache.helix.manager.zk.ZkBaseDataAccessor.get(ZkBaseDataAccessor.java:474), org.apache.helix.manager.zk.ZKHelixDataAccessor.getProperty(ZKHelixDataAccessor.java:290), org.apache.helix.controller.dataproviders.BaseControllerDataProvider.updateMaintenanceInfo(BaseControllerDataProvider.java:297), org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:335), org.apache.helix.controller.dataproviders.ResourceControllerDataProvider.refresh(ResourceControllerDataProvider.java:143), org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)]. Will not continue to next pipeline
38801169 [HelixController-pipeline-task-CLUSTER_TestWorkflowTimeout-(afd55339_TASK)] ERROR org.apache.helix.controller.GenericHelixController  - Exception while executing TASK pipeline: CLUSTER_TestWorkflowTimeout for cluster [org.apache.helix.zookeeper.zkclient.ZkClient.retryUntilConnected(ZkClient.java:1683), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1038), org.apache.helix.zookeeper.zkclient.ZkClient.getChildren(ZkClient.java:1031), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildNames(ZkBaseDataAccessor.java:670), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildren(ZkBaseDataAccessor.java:626), org.apache.helix.manager.zk.ZkBaseDataAccessor.getChildren(ZkBaseDataAccessor.java:602), org.apache.helix.manager.zk.ZKHelixDataAccessor.getChildValues(ZKHelixDataAccessor.java:415), org.apache.helix.manager.zk.ZKHelixDataAccessor.getChildValuesMap(ZKHelixDataAccessor.java:476), org.apache.helix.common.caches.PropertyCache.doSimpleCacheRefresh(PropertyCache.java:168), org.apache.helix.common.caches.PropertyCache.refresh(PropertyCache.java:160), org.apache.helix.controller.dataproviders.BaseControllerDataProvider.doRefresh(BaseControllerDataProvider.java:333), org.apache.helix.controller.dataproviders.WorkflowControllerDataProvider.refresh(WorkflowControllerDataProvider.java:88), org.apache.helix.controller.stages.ReadClusterDataStage.process(ReadClusterDataStage.java:63), org.apache.helix.controller.pipeline.Pipeline.handle(Pipeline.java:68), org.apache.helix.controller.GenericHelixController.handleEvent(GenericHelixController.java:769), org.apache.helix.controller.GenericHelixController.access$500(GenericHelixController.java:128), org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run(GenericHelixController.java:1399)]. Will not continue to next pipeline
TestWorkflowTimeout has active threads cnt:1606
zookeeper server threads has 4 thread
Failure zkclient/zooKeeper session threads has 312 thread
0 thread:main-EventThread
1 thread:HelixController-pipeline-default-TestCorrectnessOnConne

Note for 8,280 seconds, or more than two hours it does not return.

code:

`    _driver.pollForWorkflowState(workflowName, 10000L, TaskState.TIMED_OUT);`

From code, it seems that blocking call in `pollForWorkflowState` is `ctx = getWorkflowContext(workflowName);`
```
  public TaskState pollForWorkflowState(String workflowName, long timeout,
      TaskState... targetStates) throws InterruptedException {
    // Wait for completion.
    long st = System.currentTimeMillis();
    WorkflowContext ctx;
    Set<TaskState> allowedStates = new HashSet<>(Arrays.asList(targetStates));

    long timeToSleep = timeout > 100L ? 100L : timeout;
    do {
      Thread.sleep(timeToSleep);
      ctx = getWorkflowContext(workflowName);
    } while ((ctx == null || ctx.getWorkflowState() == null
        || !allowedStates.contains(ctx.getWorkflowState()))
        && System.currentTimeMillis() < st + timeout);

    if (ctx == null || !allowedStates.contains(ctx.getWorkflowState())) {
      throw new HelixException(String.format(
          "Workflow \"%s\" context is empty or not in states: \"%s\", current state: \"%s\"",
          workflowName, Arrays.asList(targetStates),
          ctx == null ? "null" : ctx.getWorkflowState().toString()));
    }

    return ctx.getWorkflowState();
  }

```

Similar to https://github.com/apache/helix/issues/1235, _propertyStore seems to hang

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
