### ISSUE TITLE
Investigate flaky test TestWorkflowTermination

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1238]
Log:
>[ERROR] Tests run: 1165, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 5,039.568 s <<< FAILURE! - in TestSuite
[ERROR] testWorkflowRunningTimeout(org.apache.helix.integration.task.TestWorkflowTermination)  Time elapsed: 10.165 s  <<< FAILURE!
org.apache.helix.HelixException: Workflow "testWorkflowRunningTimeout" context is null or job "testWorkflowRunningTimeout_TestJob" is not in states: [TIMED_OUT]
	at org.apache.helix.integration.task.TestWorkflowTermination.testWorkflowRunningTimeout(TestWorkflowTermination.java:126)

code 

```
    _driver.pollForJobState(workflowName, getJobNameToPoll(workflowName, JOB_NAME), 10000L,
        TaskState.TIMED_OUT);
```

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
