### ISSUE TITLE
Fix flaky test TestRoutingTableProviderPeriodicRefresh

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1250]
- The test purely relies on timing. Frequent source of failure. 

- The second problem is that when failed, it would leak threads in RoutingProvider which would clog the test output. (This is fixed by adding tearing down logic to @afterClass.

LOG:

>[ERROR] testPeriodicRefresh(org.apache.helix.integration.spectator.TestRoutingTableProviderPeriodicRefresh)  Time elapsed: 2.019 s  <<< FAILURE!
java.lang.AssertionError: expected:<7> but was:<6>
        at org.apache.helix.integration.spectator.TestRoutingTableProviderPeriodicRefresh.testPeriodicRefresh(TestRoutingTableProviderPeriodicRefresh.java:214)

Code:

```
public void testPeriodicRefresh() throws InterruptedException {
    // This test purely relies on sleep(). Frequent failure source, need refactor
    // Wait so that initial refreshes finish (not triggered by periodic refresh timer)
    Thread.sleep(1000L);

    // Test short refresh
    int prevRefreshCount = _routingTableProvider.getRefreshCount();
```

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
