### ISSUE TITLE
Fix TestP2PNoDuplicatedMessage leak 20 timer threads.

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1258]
LOG:
>END testP2PStateTransitionEnabled at Wed Aug 12 04:07:10 PDT 2020, took: 20243ms.
AfterClass: TestP2PNoDuplicatedMessage of TestP2PNoDuplicateMessage called.
END TestP2PNoDuplicatedMessage at Wed Aug 12 04:07:10 PDT 2020
AfterClass:TestP2PNoDuplicatedMessage afterclass of ZkTestBase called!
TestP2PNoDuplicatedMessage has active threads cnt:51
zookeeper server threads has 4 thread
zkclient/zooKeeper session threads has 8 thread
Failure fork join pool threads has 11 thread
0 thread:ForkJoinPool.commonPool-worker-4
1 thread:ForkJoinPool.commonPool-worker-13
2 thread:ForkJoinPool.commonPool-worker-2
3 thread:ForkJoinPool.commonPool-worker-6
4 thread:ForkJoinPool.commonPool-worker-10
5 thread:ForkJoinPool.commonPool-worker-8
6 thread:ForkJoinPool.commonPool-worker-1
7 thread:ForkJoinPool.commonPool-worker-3
8 thread:ForkJoinPool.commonPool-worker-11
9 thread:ForkJoinPool.commonPool-worker-15
10 thread:ForkJoinPool.commonPool-worker-9
Failure timer threads has 20 thread
0 thread:HelixTaskExecutor_Timer
1 thread:HelixTaskExecutor_Timer
2 thread:HelixTaskExecutor_Timer
3 thread:HelixTaskExecutor_Timer
4 thread:HelixTaskExecutor_Timer
5 thread:HelixTaskExecutor_Timer
6 thread:HelixTaskExecutor_Timer
7 thread:HelixTaskExecutor_Timer
8 thread:HelixTaskExecutor_Timer
9 thread:HelixTaskExecutor_Timer
10 thread:HelixTaskExecutor_Timer
11 thread:HelixTaskExecutor_Timer
12 thread:HelixTaskExecutor_Timer
13 thread:HelixTaskExecutor_Timer
14 thread:HelixTaskExecutor_Timer
15 thread:HelixTaskExecutor_Timer
16 thread:HelixTaskExecutor_Timer
17 thread:HelixTaskExecutor_Timer
18 thread:HelixTaskExecutor_Timer
19 thread:HelixTaskExecutor_Timer
Failure Other threads has 4 thread
0 thread:Monitor Ctrl-Break
1 thread:pool-36-thread-1
2 thread:main
3 thread:CallbackHandler-AsycSubscribe-Singleton
---------- Test Class TestP2PNoDuplicatedMessage thread leakage detected! ---------------

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
