### ISSUE TITLE
Change TestInstanceAutoJoin to adapt to cloud environment

### ISSUE THREAD

**Issue by zhangmeng916** [apache/helix#1264]
**Describe the bug**
The previous test `testAutoRegistrationShouldFailWhenWaitingRespons` in TestInstanceAutoJoin will fail in github test, although it always pass locally. The reason is that the test was written with the assumption that it is only run in on-prem environment and auto registration will fail with no cloud response returned. However, github tests are run in cloud environment, and the auto registration will succeed. So we need to change the tests to make it adapt to both on-prem and cloud environment.

**To Reproduce**
Run the test in github.

**Expected behavior**
Auto registration succeeds and live instance is added.

**Comment by kaisun2000** [comment]
This is the same issue as https://github.com/apache/helix/issues/1260, which has the details of why we believe so.
