### ISSUE TITLE
fix flaky test TestAutoRebalancce

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1274]
This one failed 3 times in github out of 10 logs examined.

```
    Thread.sleep(100);
    result = ClusterStateVerifier.verifyByPolling(
        new ExternalViewBalancedVerifier(_gZkClient, CLUSTER_NAME, TEST_DB), 10000, 100);
    Assert.assertTrue(result);    ---> this line fails.
```

Maybe it did note wait log enough for this ExternalViewBalancedVerifie. Need to add a log for distinguish the failure cause.

log:
>2020-08-12T03:55:06.4705923Z [ERROR] testAutoRebalance(org.apache.helix.integration.rebalancer.TestAutoRebalance)  Time elapsed: 10.969 s  <<< FAILURE!
2020-08-12T03:55:06.4710172Z java.lang.AssertionError: expected:<true> but was:<false>
2020-08-12T03:55:06.4716402Z         at org.apache.helix.integration.rebalancer.TestAutoRebalance.testAutoRebalance(TestAutoRebalance.java:177)
2020-08-12T03:55:06.4717251Z

**Comment by kaisun2000** [comment]
This could be similar to https://github.com/apache/helix/issues/1268. Though validation is not easy. Maybe by reducing the ExternalViewBalancedVerifier polling time out, if it fails consistently, we can confirm.

**Comment by kaisun2000** [comment]
Wait longer before polling to cluster converge and using correct AutoRebalancer class with AutoRebalancer strategy

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
