### ISSUE TITLE
Fix TestEnqueueJobs.testQueueJobsMaxCapacity

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1278]
github log:
>2020-08-14T23:50:43.0367342Z [ERROR]   TestClusterInMaintenanceModeWhenReachingMaxPartition.testDisableCluster:119 expected:<true> but was:<false>

>2020-08-14T23:50:42.7831939Z [ERROR] testQueueJobsMaxCapacity(org.apache.helix.integration.task.TestEnqueueJobs)  Time elapsed: 302.201 s  <<< FAILURE!
2020-08-14T23:50:42.7833487Z org.apache.helix.HelixException: Workflow "testQueueJobsMaxCapacity" context is null or job "testQueueJobsMaxCapacity_JOB2" is not in states: [COMPLETED]
2020-08-14T23:50:42.7833641Z 	at org.apache.helix.integration.task.TestEnqueueJobs.testQueueJobsMaxCapacity(TestEnqueueJobs.java:205)

**Comment by kaisun2000** [comment]
```
    for (int i = 0; i < numberOfJobsAddedInitially; i++) {
      _driver.pollForJobState(queueName, TaskUtil.getNamespacedJobName(queueName, "JOB" + i),
          TaskState.COMPLETED);
    }
```
pollForJobState is following, timeout is 5 minutes. Enable to 15 minutes with test case time to 10 minute to have a try. Also, add more about if ctx is null or the other case.

```
   long st = System.currentTimeMillis();
    do {
      Thread.sleep(timeToSleep);
      ctx = getWorkflowContext(workflowName);
    } while ((ctx == null || ctx.getJobState(jobName) == null
        || !allowedStates.contains(ctx.getJobState(jobName)))
        && System.currentTimeMillis() < st + timeout);

    if (ctx == null || !allowedStates.contains(ctx.getJobState(jobName))) {
      throw new HelixException(
          String.format("Workflow \"%s\" context is null or job \"%s\" is not in states: %s",
              workflowName, jobName, allowedStates));
    }
```

**Comment by kaisun2000** [comment]
#1346

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
