### ISSUE TITLE
Fix TestZkCallbackHandlerLeak 

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1284]
LOG: log 279
>TestZkCallbackHandlerLeak.testCurrentStatePathLeakingByAsycRemoval:494 » ThreadTimeout
> 2020-08-16T06:53:59.4439165Z [ERROR] testCurrentStatePathLeakingByAsycRemoval(org.apache.helix.integration.TestZkCallbackHandlerLeak)  Time elapsed: 900.004 s  <<< FAILURE!
2020-08-16T06:53:59.4439856Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testCurrentStatePathLeakingByAsycRemoval() didn't finish within the time-out 900000
2020-08-16T06:53:59.4440470Z 	at org.apache.helix.integration.TestZkCallbackHandlerLeak.testCurrentStatePathLeakingByAsycRemoval(TestZkCallbackHandlerLeak.java:494)

Exception:
>2020-08-16T05:31:09.7241168Z 1860741 [TestNGInvoker-testCbHandlerLeakOnControllerSessionExpiry()] ERROR org.apache.helix.TestHelper  - verifier time out, consider try longer timeout, stack trace[java.lang.Thread.getStackTrace(Thread.java:1559), org.apache.helix.TestHelper.verify(TestHelper.java:804), org.apache.helix.integration.TestZkCallbackHandlerLeak.testCbHandlerLeakOnControllerSessionExpiry(TestZkCallbackHandlerLeak.java:242), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62), sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.lang.reflect.Method.invoke(Method.java:498), org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76), org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46), org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37), java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511), java.util.concurrent.FutureTask.run(FutureTask.java:266), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)]

**Comment by jiajunwang** [comment]
The test is still not stable due to a different problem. Reopen and I will keep improving it.
The new error,
> testCurrentStatePathLeakingByAsycRemoval(org.apache.helix.integration.TestZkCallbackHandlerLeak) Time elapsed: 900.016 s

The test was stuck on shutting down the routing table provider;

**Comment by jiajunwang** [comment]
Root caused here, https://github.com/apache/helix/issues/1748

It is no longer a test issue.
