### ISSUE TITLE
Fix TestQuotaBasedScheduling.testJobQueueScheduling

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1285]
LOG: log 279
>2020-08-16T06:53:59.5273220Z [ERROR]   TestQuotaBasedScheduling.testJobQueueScheduling:556 expected:<5> but was:<4>

>2020-08-16T06:53:59.4436200Z [ERROR] testJobQueueScheduling(org.apache.helix.integration.task.TestQuotaBasedScheduling)  Time elapsed: 2.298 s  <<< FAILURE!
2020-08-16T06:53:59.4436595Z java.lang.AssertionError: expected:<5> but was:<4>
2020-08-16T06:53:59.4436940Z 	at org.apache.helix.integration.task.TestQuotaBasedScheduling.testJobQueueScheduling(TestQuotaBasedScheduling.java:556)
2020-08-16T06:53:59.4437200Z

Code:
```
   for (int i = 5; i < 10; i++) {
      String jobName = "JOB_" + i;
      lastJobName = jobName;
      _driver.enqueueJob(queueName, jobName, jobConfigBulider);
    }
    _driver.resume(queueName);
    _driver.pollForJobState(queueName, queueName + "_" + lastJobName, TaskState.COMPLETED);

    // Check run counts for each quota type
    Assert.assertEquals((int) _quotaTypeExecutionCount.get("A"), 5);
    Assert.assertEquals((int) _quotaTypeExecutionCount.get("B"), 5);   ---> failure
    Assert.assertFalse(_quotaTypeExecutionCount.containsKey(DEFAULT_QUOTA_TYPE));
```

Note `_driver.pollForJobState(queueName, queueName + "_" + lastJobName, TaskState.COMPLETED);` did not throw exception. This is a genuine issue. Need someone knows the test well to have a look.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
