### ISSUE TITLE
Fix unstable test TestZKCallback

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1288]
LOG:
>2020-08-16T23:12:01.3630643Z [ERROR]   TestZKCallback.testInvocation:188

>2020-08-16T23:12:01.1107126Z [ERROR] testInvocation(org.apache.helix.TestZKCallback)  Time elapsed: 1.37 s  <<< FAILURE!
2020-08-16T23:12:01.1107570Z java.lang.AssertionError: 
2020-08-16T23:12:01.1108063Z 	at org.apache.helix.TestZKCallback.testInvocation(TestZKCallback.java:188)
2020-08-16T23:12:01.1108312Z 

This one is similar to #1233

**Comment by kaisun2000** [comment]
#1227 addresses this issue.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
