### ISSUE TITLE
Fix flaky test TestTaskAssignmentCalculator.testAbortTaskForWorkflowFail

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1289]
LOG:
> 2020-08-17T22:06:07.0720623Z [ERROR] testAbortTaskForWorkflowFail(org.apache.helix.integration.task.TestTaskAssignmentCalculator)  Time elapsed: 2.07 s  <<< FAILURE!
2020-08-17T22:06:07.0723951Z java.lang.AssertionError: expected:<4> but was:<3>
2020-08-17T22:06:07.0731376Z 	at org.apache.helix.integration.task.TestTaskAssignmentCalculator.testAbortTaskForWorkflowFail(TestTaskAssignmentCalculator.java:206)

> 2020-08-17T22:06:07.4228034Z [ERROR]   TestTaskAssignmentCalculator.testAbortTaskForWorkflowFail:206 expected:<4> but was:<3>

Code:

```
    _driver.pollForWorkflowState(workflowName, TaskState.FAILED);

    int abortedTask = 0;
    for (TaskState jobState : _driver.getWorkflowContext(workflowName).getJobStates().values()) {
      if (jobState == TaskState.ABORTED) {
        abortedTask++;
      }
    }

```

**Comment by kaisun2000** [comment]
```
 public TaskState pollForWorkflowState(String workflowName, long timeout,
      TaskState... targetStates) throws InterruptedException {
    // Wait for completion.
    long st = System.currentTimeMillis();
    WorkflowContext ctx;
    Set<TaskState> allowedStates = new HashSet<>(Arrays.asList(targetStates));

    long timeToSleep = timeout > 100L ? 100L : timeout;
    do {
      Thread.sleep(timeToSleep);
      ctx = getWorkflowContext(workflowName);
    } while ((ctx == null || ctx.getWorkflowState() == null
        || !allowedStates.contains(ctx.getWorkflowState()))
        && System.currentTimeMillis() < st + timeout);

    if (ctx == null || !allowedStates.contains(ctx.getWorkflowState())) {
      throw new HelixException(String.format(
          "Workflow \"%s\" context is empty or not in states: \"%s\", current state: \"%s\"",
          workflowName, Arrays.asList(targetStates),
          ctx == null ? "null" : ctx.getWorkflowState().toString()));
    }

    return ctx.getWorkflowState();
  }


```

Is it possible that only one job failing would cause workflow failure? `!allowedStates.contains(ctx.getWorkflowState()))`

**Comment by kaisun2000** [comment]
// Note, the starting tasks messages are send out at the same time.
    // There is no guarante only one task would fail. In fact 5 tasks run in parallel in
    // 5 instances. There can be multiple task failing.
    Assert.assertTrue(abortedTask <= 4);
    Assert.assertEquals(_runCounts.size(), 5);

**Comment by kaisun2000** [comment]
log4j.logger.org.apache.helix.controller.stages.MessageDispatchStage=INFO

to validate.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism #1757 now for tracking the most recent test issues.
