### ISSUE TITLE
Fix unstable TestEnqueueJobs.testQueueParallelJobs

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1290]
LOG: (306)
> 2020-08-18T11:30:10.5298222Z [ERROR]   TestEnqueueJobs.testQueueParallelJobs » ThreadTimeout Method org.testng.intern...

> 2020-08-18T11:30:10.1445085Z [ERROR] testQueueParallelJobs(org.apache.helix.integration.task.TestEnqueueJobs)  Time elapsed: 899.988 s  <<< FAILURE!
2020-08-18T11:30:10.1455789Z org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testQueueParallelJobs() didn't finish within the time-out 900000
2020-08-18T11:30:10.1457141Z

**Comment by kaisun2000** [comment]
This one is similar to #1278. 

1/ Add test start and end log message

2/ enlarge timeout value.

**Comment by kaisun2000** [comment]
#1346

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
