### ISSUE TITLE
Router completely reset when receives FINALIZE event

### ISSUE THREAD

**Issue by mgao0** [apache/helix#1296]
### Describe the bug
When handle child changes in CallbackHandler, under certain condition we will remove the listener.
When we dropped a customized state type (TYPE_C for example), the associated customized view path and its children nodes for this customized state type is deleted, so the callback handler is finalized. An example for the path would be: /cluster_name/CUSTOMIZEDVIEW/TYPE_C, /cluster_name/CUSTOMIZEDVIEW/TYPE_C/resource_name

@Override
  public void handleChildChange(String parentPath, List<String> currentChilds) {
    if (logger.isDebugEnabled()) {
      logger.debug("Data change callback: child changed, path: {} , current child count: {}",
          parentPath, currentChilds == null ? 0 : currentChilds.size());
    }

    try {
      updateNotificationTime(System.nanoTime());
      if (parentPath != null && parentPath.startsWith(_path)) {
        if (currentChilds == null && parentPath.equals(_path)) {
          // _path has been removed, remove this listener
          // removeListener will call handler.reset(), which in turn call invoke() on FINALIZE type
          _manager.removeListener(_propertyKey, _listener);
        } else {
          if (!isReady()) {
            // avoid leaking CallbackHandler
            logger.info("Callbackhandler {} with path {} is in reset state. Stop subscription to ZK client to avoid leaking",
                this, parentPath);
            return;
          }
          NotificationContext changeContext = new NotificationContext(_manager);
          changeContext.setType(NotificationContext.Type.CALLBACK);
          changeContext.setPathChanged(parentPath);
          changeContext.setChangeType(_changeType);
          subscribeForChanges(changeContext.getType(), _path, _watchChild);
          enqueueTask(changeContext);
        }
      }
    } catch (Exception e) {
      String msg = "exception in handling child-change. instance: " + _manager.getInstanceName()
          + ", parentPath: " + parentPath + ", listener: " + _listener;
      ZKExceptionHandler.getInstance().handle(msg, e);
    }
  }

This will send a FINALIZE event to the routing table provider which is listening on this path.
When routing table provider handles this event, it calls reset() and the entire routing table will be reset.
`if (changeContext.getType() == NotificationContext.Type.FINALIZE) {
        reset();
      }
`

It caused problems in customized view feature, that when an aggregation enabled customized state type is dropped from customized view, a FINALIZE event is sent to the routing table provider, and triggers the reset of routing table. If there is on more events incoming, we will see an empty routing table.

### To Reproduce
Initialize a routing table provider listening to customized state type A and B, set aggregation enabled customized state types in controller to be A andB, update some customized states for both types. Then set aggregation enabled customized state types in controller to be only A, and get routing table snapshot from routing table provider, and the routing table is empty.
 
### Expected behavior
We can fix this in two ways:
1. Fix callback handler, so it doesn't enqueue FINALIZE event for the change. For example, in the above piece of code, for CurrentState, when dropping a resource, the callback handler enqueue a CALLBACK typed event, so the routing table provider won't be reset unexpectedly. 
2. Add granularity into routing table provider, so we don't reset the entire routing table provider when getting FINALIZE event on one path. 

### Additional context
Current work around https://github.com/apache/helix/pull/1302
Use more incoming event to trigger refresh of routing table

**Comment by kaisun2000** [comment]
It seems that currentState based RP has one callbackhandler with all currentstate as child znode. Thus reset would refresh all currentstate only once. This is fine.
CustomizedView for each type has one callbackHandler. Thus, one removal of callbackhandler parent path would cause other types of customizedView be reset() too.

In sum, current design of routingProvider accomodate only one callbackhandler. (External view, currentstate). However customized view RP has callbackhandler per type. This does not fit into the current design of RP.

@jiajunwang , @zhangmeng916, is the above description right?
