### ISSUE TITLE
Fix unstable test TestPartitionLevelTransitionConstraint

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1316]
LOG:
>[ERROR] test(org.apache.helix.integration.TestPartitionLevelTransitionConstraint)  Time elapsed: 0.691 s  <<< FAILURE!
java.lang.AssertionError: expected:<7> but was:<5>
        at org.apache.helix.integration.TestPartitionLevelTransitionConstraint.test(TestPartitionLevelTransitionConstraint.java:177)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestPartitionLevelTransitionConstraint.test:177 expected:<7> but was:<5>
[INFO] 
[ERROR] Tests run: 1170, Failures: 1, Errors: 0, Skipped: 0

**Comment by kaisun2000** [comment]
Add logging now to see what the `Assert.assertEquals(_msgOrderList.size(), 7, "_msgOrderList is:" + _msgOrderList.toString());`

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism #1757 now for tracking the most recent test issues.
