### ISSUE TITLE
fix TestFullAutoNodeTagging.testSafeAssignment

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1393]
LOG 1235 after delayedAuto as default

>2020-09-23T03:14:06.1737876Z [ERROR] testSafeAssignment(org.apache.helix.integration.rebalancer.TestFullAutoNodeTagging)  Time elapsed: 32.957 s  <<< FAILURE!
2020-09-23T03:14:06.1739684Z java.lang.AssertionError: expected:<true> but was:<false>
2020-09-23T03:14:06.1741742Z 	at org.apache.helix.integration.rebalancer.TestFullAutoNodeTagging.testSafeAssignment(TestFullAutoNodeTagging.java:300)

```
      if (taggedNodes.contains(instanceName)) {
        // make sure that the best possible matches the external view
        Thread.sleep(500);
        boolean result =
            ClusterStateVerifier.verifyByZkCallback(new BestPossAndExtViewZkVerifier(ZK_ADDR,
                clusterName));
        Assert.assertTrue(result);

```

**Comment by kaisun2000** [comment]
START TestFullAutoNodeTagging_testSafeAssignment at Tue Sep 22 22:01:39 PDT 2020
0    [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(f23303a1_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
24   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(fadbd556_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
32   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(f21f0ad2_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
38   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(2a2175b5_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
44   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(e3221ee4_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
58   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(ea9dba6c_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
66   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(0e952013_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
76   [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(1e6ea235_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
328580 [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(d515f963_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
328592 [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(ec6849fd_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
328612 [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(3442e8cb_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []
328617 [HelixController-pipeline-default-TestFullAutoNodeTagging_testSafeAssignment-(6d028faa_DEFAULT)] ERROR org.apache.helix.controller.rebalancer.DelayedAutoRebalancer  - No instances or active instances available for resource TestDB0, allInstances: [localhost_12922, localhost_12924, localhost_12925, localhost_12920], liveInstances: [], activeInstances: []

**Comment by kaisun2000** [comment]
{
  "id" : "TestDB0",
  "simpleFields" : {
    "IDEAL_STATE_MODE" : "AUTO_REBALANCE",
    "INSTANCE_GROUP_TAG" : "ASSIGNABLE",
    "NUM_PARTITIONS" : "4",
    "REBALANCE_MODE" : "FULL_AUTO",
    "REBALANCE_STRATEGY" : "DEFAULT",
    "REPLICAS" : "2",
    "STATE_MODEL_DEF_REF" : "MasterSlave",
    "STATE_MODEL_FACTORY_NAME" : "DEFAULT"
  },
  "mapFields" : {
    "TestDB0_0" : { },
    "TestDB0_1" : { },
    "TestDB0_2" : { },
    "TestDB0_3" : { }
  },
  "listFields" : {
    "TestDB0_0" : [ ],
    "TestDB0_1" : [ ],
    "TestDB0_2" : [ ],
    "TestDB0_3" : [ ]
  }
}

**Comment by kaisun2000** [comment]
Similar to #1392

**Comment by kaisun2000** [comment]
This case seems to be DelayedAutoRebalancer with AutoRebalanceStrategy

**Comment by kaisun2000** [comment]
we need DelayAuto + crushed.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
