### ISSUE TITLE
fix TestClusterMaintenanceMode.testMaintenanceHistory

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1402]
LOG 1349

>2020-09-24T05:57:40.9661144Z [ERROR] testMaintenanceHistory(org.apache.helix.integration.controller.TestClusterMaintenanceMode)  Time elapsed: 0.012 s  <<< FAILURE!
2020-09-24T05:57:40.9663283Z java.lang.AssertionError: expected:< ENTER> but was:< EXIT>
2020-09-24T05:57:40.9666348Z 	at org.apache.helix.integration.controller.TestClusterMaintenanceMode.testMaintenanceHistory(TestClusterMaintenanceMode.java:345)
2020-09-24T05:57:40.9673712Z

**Comment by kaisun2000** [comment]
```
  @Test(dependsOnMethods = "testMaxPartitionLimit")
  public void testMaintenanceHistory() throws InterruptedException, IOException {
    // In maintenance mode, by controller, for MAX_PARTITION_PER_INSTANCE_EXCEEDED
    ControllerHistory history = _dataAccessor.getProperty(_keyBuilder.controllerLeaderHistory());
    Map<String, String> lastHistoryEntry = convertStringToMap(
        history.getMaintenanceHistoryList().get(history.getMaintenanceHistoryList().size() - 1));

    // **The KV pairs are hard-coded in here for the ease of reading!**
    Assert.assertEquals(lastHistoryEntry.get("OPERATION_TYPE"), "ENTER");              -----> this line failed.
    Assert.assertEquals(lastHistoryEntry.get("TRIGGERED_BY"), "CONTROLLER");
    Assert.assertEquals(lastHistoryEntry.get("AUTO_TRIGGER_REASON"),
        "MAX_PARTITION_PER_INSTANCE_EXCEEDED");

```

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
