### ISSUE TITLE
Java doc is not generated since 0.7

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#1427]
### Describe the bug
http://helix.apache.org/javadocs/ you can see that we are not generating java doc recently.
The link in our home page does not work.

### To Reproduce
http://helix.apache.org/javadocs/

### Expected behavior
http://helix.apache.org/javadocs/ for the later version should be generated.

**Comment by groelofs** [comment]
Still broken two and a half years later.

**Comment by desaikomal** [comment]
@groelofs - hope that this will fix it: https://github.com/apache/helix/pull/2510

thanks,
komal
