### ISSUE TITLE
MultiOp support in the Helix ZkClient

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#1428]
**Is your feature request related to a problem? Please describe.**
The native multi ops method does not fit Helix ZkClient so it is hard for us to use correctly. It relies on the caller to do serialize, validation, and monitor.

**Describe the solution you'd like**
Introduce a new multiOp method in the Helix ZkClient which contains all the default Helix ZkClient enhanced features.

**Additional context**

**Comment by kaisun2000** [comment]
This multi() is targeted to fix recently identified "phantom" read problem when refreshing the cache using selective update. I will create a separate issue to illustrate the "phantom read" separately.

**Comment by jiajunwang** [comment]
> This multi() is targeted to fix recently identified "phantom" read problem when refreshing the cache using selective update. I will create a separate issue to illustrate the "phantom read" separately.

Yeah please do so. This issue is for feature requests and not only targeting fixing the "phantom" read issue. We need this feature in many other places. Also as the provider of the lib, we shall provide consistent ZkClient APIs that behave in the same fashion. Unfortunately, the existing multiOp method does not meet the bar.

**Comment by xyuanlu** [comment]
We already have Multi() support in ZkClient.
