### ISSUE TITLE
Pausing controller may not work when controller leadership transfers

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1442]
This issue was raised from code review of #1066, though it is not this pull introduced the issue.

First pause signal is added, the old lead controller see this one and the callback is in zkclient queue. The new lead controller to be also see it, but the generic controller ignored it as it is not leader yet. Then new controller becomes leader due to old controller session expiration. 

Here, will the new controller not stopped?

Will the new controller do a full refresh and see the pause signal. Will the new controller stop then?

**Comment by jiajunwang** [comment]
On my understanding, the new controller shall read all znodes including the signal once it get the leadership. So it will be paused. Please try to reproduce.

**Comment by jiajunwang** [comment]
@kaisun2000 please follow the issue template if possible. If we have a way to confirm if this is an real issue, let's do so. If it requires more time, please mark it as a task which titled with "Confirming if XXX is a bug".
