### ISSUE TITLE
Fix task related unstable unit test

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#1454]
Currently selective update can result in "phantom read". For example, when job1 cfg is added and then workflow cfg containing job 1 is updated. The selective update may only see updated workflow cfg but not job 1 cfg. This would cause job1 cfg and ctx removed. THus hanging tests.

Currently we work around this issue by setting purge interval to -1 and enhance logging in task to make test stable.

**Comment by jiajunwang** [comment]
Close test unstable tickets since we have an automatic tracking mechanism https://github.com/apache/helix/pull/1757 now for tracking the most recent test issues.
