### ISSUE TITLE
Clean shutdown of controllers and participants

### ISSUE THREAD

**Issue by bfreuden** [apache/helix#1518]
### Describe the bug

When you create a ``HelixManager`` then disconnect it with ``manager.disconnect();`` the JVM cannot naturally exit because the 
`` org.apache.helix.manager.zk.CallbackHandler`` has a private static field called ``SubscribeChangeEventProcessor`` that is a running Thread.

### To Reproduce
Granted the following program is not very useful (starting and stopping a participant) but it cannot exit naturally:
```java
    public static void main(String[] args) {
        HelixManager manager = HelixManagerFactory.getZKHelixManager(
                CLUSTER_NAME, "localhost_7000", InstanceType.PARTICIPANT, ZK_ADDRESS);
        try {
            StateMachineEngine stateMach = manager.getStateMachineEngine();
            StateModelFactory stateModelFactory = getStateModelFactory();
            stateMach.registerStateModelFactory(STATE_MODEL_NAME, stateModelFactory);
            manager.connect();
            Runtime.getRuntime().addShutdownHook(new HelixManagerShutdownHook(manager));
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            manager.disconnect();
        }
    }
```

### Expected behavior

I was expecting a programmatic way to terminate all Helix threads.
For the moment I have this solution:
```java
        } finally {
            manager.disconnect();
            try {
                Field field = CallbackHandler.class.getDeclaredField("SubscribeChangeEventProcessor");
                field.setAccessible(true);
                Thread thread = (Thread)field.get(null);
                thread.interrupt();
            } catch (NoSuchFieldException | IllegalAccessException e) {
                e.printStackTrace();
            }
        }
```

### Possible solution

I have the impression that if the ``SubscribeChangeEventProcessor`` Thread was a daemon thread, it would be enough.

**Comment by mebe** [comment]
According to https://github.com/apache/helix/pull/300#issuecomment-460855943 `SubscribeChangeEventProcessor ` cannot be deamonized. Has the situation changed?

**Comment by bfreuden** [comment]
@mebe thanks for pointing at this ticket and comment: I was not aware of it.

Although it sounds strange to me, I am ready to accept the ``SubscribeChangeEventProcessor`` can't be daemonized. 
I have the feeling we need a way to terminate an Helix application properly though.
Otherwise it means that the application has to be killed and I don't know if that will trigger a proper "finalization of all handlers" (just quoting the comment here, I don't understand what it means).
In my experience, once the JVM has decided to stop, there's not much you can do... even in the shutdown hooks. That's why I've always considered it best to have a "clean shutown" function so the application can schedule its own shutdown properly, without any rush.

**Comment by junkaixue** [comment]
The ticket is old and I think the problem has been resolved.
