### ISSUE TITLE
The static map of GenericHelixController could be overwritten if create multiple controllers for the same cluster in one JVM

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#1617]
### Describe the bug
A static map of GenericHelixController is used to track all the controllers that are created in the JVM. This record is used to find the required controller object using the cluster name. However, if we run multiple controllers for a single cluster in one JVM, then these records will overwrite each other.

The problem usually happens in test when we need to simulate controller leadership election. But it may also happen in prod environment if we use a single JVM to run multiple controller instances.
One of the direct failures is that the scheduleOnDemandPipeline() method will fail since it cannot find the right controller instance from the map.
Note that this impacts WAGED rebalancer (and maybe TF logics) since they rely on the schedule method to trigger later rebalance.

### To Reproduce
In one JVM, create multiple controller instances for the same cluster. Then try to schedule an on-demand rebalance by using WAGED rebalance or Task framework features. In detail, just try to make some changes in the cluster which has WAGED usage, or TF usage. Then the scheduling of on-demand rebalance shall fail since the code cannot find the right controller to send schedule requests.

### Expected behavior
The rebalance schedule request shall be sent to the current leader controller. And the request shall be accepted and triggered normally.

### Additional context
The following link points to the problematic code.
https://github.com/apache/helix/blob/361e18da4152c0146daa9d9dc7929f1f2bdcd9dc/helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java#L228

**Comment by narendly** [comment]
Would adding a isLeader() check prevent this scenario here? https://github.com/apache/helix/blob/361e18da4152c0146daa9d9dc7929f1f2bdcd9dc/helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java#L656

**Comment by jiajunwang** [comment]
> Would adding a isLeader() check prevent this scenario here?
> 
> https://github.com/apache/helix/blob/361e18da4152c0146daa9d9dc7929f1f2bdcd9dc/helix-core/src/main/java/org/apache/helix/controller/GenericHelixController.java#L656

Possible but not necessarily the best solution. The leadership could be changed at any time. However, there is no existing way to modify the record in the map after the controller instance is created.
