### ISSUE TITLE
Rebalance Apache Helix Manager when an instance in the cluster comes down

### ISSUE THREAD

**Issue by arindamc2000** [apache/helix#1622]
### To Reproduce
I have a spring boot application through which I am trying to add/remove instances from a Helix Cluster.
When ever I add an instance the  cluster is getting rebalanced properly.
Here is a piece of code I am using for it.

zkHelixAdmin.rebalance(Configuration.getHeCluster(), resourceName(), instancesInCluster.size())).

However when an instance comes down gracefully, I try to get hold of a shutdown hook and invoke the rebalance for instancesInCluster.size()-1.
This is were I am getting stuck due to this error :

org.apache.helix.HelixException: Resource: Cluster has NOT been added yet.

The shutdown hook looks like this:

@Configuration
public class ShutdownHookConfiguration {

    @Bean(destroyMethod = "destroy")
    public Bean1 initializeBean3() {
        return new Bean1();
    }
}

and Bean1 is where I am trying to do the rebalance.
Any guidance around this will be really appreciated.

**Comment by narendly** [comment]
@arindamc2000  Seems like you are manually triggering a rebalance when an application exits/shuts down. Are you aware that Helix supports a Full-auto mode where this is done all automatically?

It sounds like full-auto should solve this issue and simplify your shutdown logic.

**Comment by arindamc2000** [comment]
@narendly I do have my cluster configured for auto rebalancing but for some reason my IdealState Rebalance mode is configured to SEMI_AUTO.
I tried this piece of code to force it to rebalance as FULL_AUTO, but that did not help:

 IdealState state = new IdealState(zkAdmin.getResourcesInCluster(trellixConfiguration.getHeCluster()).get(0));
                state.setRebalanceMode(RebalanceMode.FULL_AUTO);
                state.setReplicas("2");
                zkAdmin.rebalance(trellixConfiguration.getHeCluster(), state, zkAdmin.getInstancesInCluster(trellixConfiguration.getHeCluster()));

**Comment by junkaixue** [comment]
Now Helix default the WAGED rebalanced to be controllers cluster rebalance. If you are in full auto with Top state constraint setup, it should get LEADERs rebalanced.
