### ISSUE TITLE
Please tidy up old releases from the mirror system

### ISSUE THREAD

**Issue by sebbASF** [apache/helix#1665]
To reduce the load on the ASF mirrors, projects are required to archive old releases [1]

It's unfair to expect the 3rd party mirrors to carry old releases.

Please can you archive all non-current releases?
[Remember to update the download page before dropping the files from dist.apache.org!]

The following releases appear to be non-current:

0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.7.1, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.0.1, 0.9.4, 0.9.7, 1.0.0

If necessary, please also update your release procedures to ensure old releases are archived
once a new release has been published.

Thanks!

[1] http://www.apache.org/dev/release.html#when-to-archive

**Comment by junkaixue** [comment]
Resolved. Deprecate 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.7.1, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.0.1, 0.9.4, 0.9.7, 1.0.0
