### ISSUE TITLE
IdealState does not appear to be written

### ISSUE THREAD

**Issue by jeff-blaisdell** [apache/helix#1670]
### Describe the bug
There appears to be a bug with either the calculation of the "DifferenceWithIdealStateGauge" metric, or the writing of ideal state.  We recently went through an upgrade from Helix 0.6.9 to 1.0.1.  When viewing the current state of Helix `--listResourceInfo`, IdealState in both 0.6.9 and 1.0.1 appears to always be empty.  However, the metric calculation seems to have changed between the two versions.  In 0.6.9, "DifferenceWithIdealStateGauge" would be emitted as 0.  In 1.0.1, it will correctly emit an accurate metric as an empty IdealState with all partitions accurately assigned will always emit the total partitions as the "DifferenceWithIdealStateGauge" metric.

// Metric calculation in 1.0.1
[(1.0.1) ResourceMonitor.java](https://github.com/apache/helix/blob/helix-1.0.1/helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ResourceMonitor.java#L243)

// Metric calculation in 0.6.9
[(0.6.9) ResourceMonitor.java](https://github.com/apache/helix/blob/helix-0.6.9/helix-core/src/main/java/org/apache/helix/monitoring/mbeans/ResourceMonitor.java#L98)

This could potentially be related to https://github.com/apache/helix/issues/609.

### To Reproduce
https://github.com/jeff-blaisdell/helix-issue contains a full working example.  Greater details on environment / cluster setup can be found in project README.

### Expected behavior
DifferenceWithIdealStateGauge should correctly report 0.

**Comment by jeff-blaisdell** [comment]
I've been doing some debugging / digging on this issue..  While studying the Helix internals I discovered reference to a config option `PERSIST_BEST_POSSIBLE_ASSIGNMENT`.  I can confirm that by setting it to true, the IdealState is properly written and the `DifferenceWithIdealStateGauge` correctly reports 0.  

```
helix-admin.sh --zkSvr localhost:2181 --setConfig CLUSTER default-cluster PERSIST_BEST_POSSIBLE_ASSIGNMENT=true
```

I haven't been able to find any documentation around the considerations of using that option, or why the default is false.

**Comment by jiajunwang** [comment]
Thanks for reporting the issue, Jeff.

Enabling the assignment persistent is required in the current version. The impact of enabling this option should be minimum. If the assignment is not changed, there won't be ZK write. However, if we have a very large IdealState znode and the cluster is being modified frequently, then the additional ZK traffic might be a burden.

I will discuss with the other stakeholders how we should improve this. But for now, enabling assignment seems to be the only option.
