### ISSUE TITLE
Add an option to always perform all checks in Helix stoppable check API

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#1688]
**Is your feature request related to a problem? Please describe.**
Helix stoppable check currently does the check in 3 sequential stages: Helix standard checks, custom instance health check and custom partition health check. When one stage had any failure, the subsequent stages are not executed.

This poses an issue that if participant happens to ignore all the failed checks in stage 1 but stage 2/3 would have reported some other failures, then it would think it's safe to stop the instance when it's in fact not safe. For example, if an instance would fail INSTANCE_NOT_STABLE in stage 1 and custom partition health check in stage 3, Helix will only return INSTANCE_NOT_STABLE and if participant ignores this failure reason, it will consider the instance safe to stop when it's not.

**Describe the solution you'd like**
Provide an option in Helix stoppable check API, such that when the option is used, Helix will always perform all checks and return all failed checks.

**Comment by jiajunwang** [comment]
I think we need to communicate a little bit more about motivation.
1. Why stage 1 Helix checks are not valid for applications. Is it fixable? Or it is fundamentally not applied.
2. Can we just let users to opt-out of the stage 1 checkup if they are not applicable? In this case, we do not waste resources to run a set of invalid checks.
3. If all the above options are not possible, do we really need to make it an option instead of just make it the default behavior?

**Comment by pkuwm** [comment]
> I think we need to communicate a little bit more about motivation.
> 
> 1. Why stage 1 Helix checks are not valid for applications. Is it fixable? Or it is fundamentally not applied.
> 2. Can we just let users to opt-out of the stage 1 checkup if they are not applicable? In this case, we do not waste resources to run a set of invalid checks.
> 3. If all the above options are not possible, do we really need to make it an option instead of just make it the default behavior?

@jiajunwang Thanks for the questions.
For example, customers have a deployment during rebalance.  During the deployment, they want to ignore INSTANCE_NOT_STABLE failure. This is because custom has state transition cancellation feature enabled, they want to stop an instance even if there is state transition going on. They only ignore certain checks and if they are the only ones that failed, then they treat it as stoppable. 
So they want all checks to determine if the instance is stoppable for this case.
For the other cases, we helix don’t have to do all checks. The current logic is still valid, if helix own fails, no need to further check custom.
