### ISSUE TITLE
Some bugs in `rsync-replicated-file-system` of recipes

### ISSUE THREAD

**Issue by astor-oss** [apache/helix#1801]
### Describe the bug

- [ ] `rsync-replicated-file-system` has different StateModeDefinition between `IntegrationTest` and `SetupCluster`
- [ ]  start script in bin directory

### To Reproduce
Steps to reproduce the behavior.
1. Execute `SetupCluster` and `IntegrationTest` to initialize the cluster configuration,  then the state is different. Just as follows:
![image](https://user-images.githubusercontent.com/6895821/122509356-391dd580-d036-11eb-981b-0e0eb3a2ea9f.png)

2.  the script in the `bin` directory has some errors, so it cannot start the cluster.

**Comment by junkaixue** [comment]
Thanks @hzxjtx . We will fix it.

**Comment by junkaixue** [comment]
Fixed: https://github.com/apache/helix/commit/8d295620d3eddebdcfbede25f221c68f63dfe0d0
