### ISSUE TITLE
Which priority rule should be used for state transition? Document? Or Annotation?

### ISSUE THREAD

**Issue by liuhuagui** [apache/helix#1829]
![image](https://user-images.githubusercontent.com/21290865/126736197-91993bc2-ef60-4d48-890b-4470097bdff0.png)
http://helix.apache.org/1.0.1-docs/tutorial_state.html
![image](https://user-images.githubusercontent.com/21290865/126736289-09bd8ecc-399e-4a96-894e-4ddc8d4bc779.png)

**Comment by jiajunwang** [comment]
The tutorial should be the correct information. I will fix the Javadoc.
