### ISSUE TITLE
Range Partitioning Support

### ISSUE THREAD

**Issue by ritesh-kapoor** [apache/helix#1836]
Apache helix to support range partitioning. 
e.g. Range : [1-100] Nodes: 3
Node 1: [0-50]
Node 2: [50-55]
Node 3: [55-100]

**Comment by junkaixue** [comment]
@ritesh-kapoor are you using the FULL_AUTO mode for helix? If yes, you can change you number of partitions and Helix will automatically generate new partitions. 

For the underneath partition index is generated by you application.

**Comment by junkaixue** [comment]
Feel free to reopen the ticket or question. close it now.
