### ISSUE TITLE
Need guideline or new API to support State Model migration with necessary vallidation

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#1843]
**Is your feature request related to a problem? Please describe.**
1. To eliminate non-inclusive language usage (MasterSlave state model), Helix customers need support to migrate their existing resources from the MS state model to the other state model. For example, LeaderFollower.
2. Other customers are looking for a safe solution to update their resources' state model. For instance, to add new customized state to the current state model. Or, completely change the logic of the current state model.

A known working solution is to rebuild the resource or bring it completely offline (then restart with the new state model). An online migration method is possible but not tested/documented.
 
**Describe the solution you'd like**
No solution is proposed now.
The goal of this ticket would be to document the Helix recommended way to migrate the state model of an existing resource. While online migration is preferred, it might need some logic changes or prolong the migration time. These trade-offs and details need to be noted down as well.

**Additional context**

**Comment by mcvsubbu** [comment]
hopefully the overall goal is to automate this and not just document. if there is an epic to handle this in an automated fashion, documentation can be the first step.

Zero service disruption is the key

**Comment by jiajunwang** [comment]
One of the reasons I don't think we can fully automate the migration process is because it requires application (participant) code changes. Otherwise, we shall try to automate and simplify as much as we can.

**Comment by junkaixue** [comment]
any update for this?

**Comment by junkaixue** [comment]
Feel free to reopen this.
