### ISSUE TITLE
Imprecise param name on the rebalance API in HelixAdmin

### ISSUE THREAD

**Issue by Lincong** [apache/helix#1876]
### Describe the bug
The rebalance method on the `HelixAdmin` is:
```
  /**
   * Rebalance a resource in cluster
   * @param clusterName
   * @param resourceName
   * @param replica
   */
  void rebalance(String clusterName, String resourceName, int replica);
```
The last param is `int replica`. It'd be more precise to name it `replicaNum` or `replicaCount` since `int replica` is ambiguous since it could mean `replica ID` etc.
In addition, please consider adding accurate description of params to its Java doc. 

### To Reproduce
Steps to reproduce the behavior.

**Comment by narendly** [comment]
Thanks @Lincong - this is good feedback. Feel free to make a Pull Request yourself. Otherwise, we could also pick this up sometime.

**Comment by Lincong** [comment]
Thanks, @narendly, which branch should I create a PR against?

**Comment by junkaixue** [comment]
@Lincong Master branch should be fine. But remember follow the OR template and steps.

**Comment by junkaixue** [comment]
Feel free to reopen it if you have a PR
