### ISSUE TITLE
Why LockListener is not public

### ISSUE THREAD

**Issue by hungvm90** [apache/helix#1893]
### Describe the bug
interface LockListener {
  /**
   * call back called when the lock is preempted
   */
  void onCleanupNotification();
}
This interface should be public

### To Reproduce
When not set LockListener, try to lock with higher priority, it throw "Cleanup has not been finished by lock owner"

### Expected behavior
interface LockListener should be public, or when not set LockListener, it should be pass

**Comment by mgao0** [comment]
@zhangmeng916 Is not set LockListener an expected user behavior? I tried making LockListener public, but it didn't solve the problem.

**Comment by zhangmeng916** [comment]
@hungvm90 The LockListener needs to be set for the lock to be able to work, since it listens on Zookeeper once there is any change in the lock path.

**Comment by hungvm90** [comment]
Sorry, my description for this issue is not correct, but I think LockListener should be public.
For example, I implement lock with priority, so I need ack when I lose this lock. But LockListener is not public, so I can't implement it.

lock = new ZKDistributedNonblockingLock.Builder()
                .setLockScope(new HelixLockScope(HelixLockScope.LockScopeProperty.RESOURCE, pathKeys))
                .setZkAddress(zooKeeperHost)
                .setUserId(instanceName)
                .setTimeout(timeout)
                .setPriority(LOCK_LOW_PRIORITY)
                .setLockListener(new LockListener() {
                    @Override
                    public void onCleanupNotification() {
                        for (LockLoseListener listener : listeners) {
                            listener.onLoseLock(lock);
                        }
                    }
                })
                .setLockMsg(String.format("Lock %s from %s", resource, instanceName))
                .build();

**Comment by junkaixue** [comment]
@hungvm90 The LockListener is an public interface. Not sure what do you mean it is not public.

**Comment by hungvm90** [comment]
https://github.com/apache/helix/blob/master/helix-lock/src/main/java/org/apache/helix/lock/helix/LockListener.java
this is package access modifier, I can't implement this interface outside package?

**Comment by junkaixue** [comment]
Make it explicit now: https://github.com/apache/helix/blob/master/helix-lock/src/main/java/org/apache/helix/lock/helix/LockListener.java

Close this issue.
