### ISSUE TITLE
GC_THREAD in ZkBucketDataAccessor is not shut down

### ISSUE THREAD

**Issue by hmhagberg** [apache/helix#1915]
### Describe the bug
`GC_THREAD` (which is actually an `ExecutorService`, not `Thread`) is a static field in `ZkBucketDataAccessor`. The executor is started when `ZkBucketDataAccessor` class is initialized but it is never shut down. Since `ExecutorService` threads are generally not daemon threads, not shutting down `GC_THREAD` prevents JVM from shutting down cleanly.

### To Reproduce
Run application which references `ZkBucketDataAccessor` class and then exits. JVM does not shut down but hangs instead.

### Expected behavior
Referencing `ZkBucketDataAccessor` class should not prevent clean exit.

### Additional context
Workaround is to make `GC_THREAD` field public using reflection and shut it down in application's own shutdown hook.

**Comment by narendly** [comment]
@hmhagberg thanks for the bug report. Feel free to create a Pull Request - we could review this as it seems like a simple fix.

**Comment by hmhagberg** [comment]
@narendly it took a while but here's PR that aims to solve the issue by daemonizing `GC_THREAD`: https://github.com/apache/helix/pull/1936

Also a small correction to reproduction steps: simply referencing `ZkBucketDataAccessor` is not enough to trigger the issue. `ThreadPoolExecutor` threads are not prestarted by default so it is necessary to schedule some task on `GC_THREAD` to create the thread and trigger the issue.
