### ISSUE TITLE
Stale message redundant logs

### ISSUE THREAD

**Issue by NealSun96** [apache/helix#1940]
### Describe the bug
Stale messages seem to be logged multiple times for unrelated resources. 

### To Reproduce
Having a stale message in a multi-resource cluster and check controller logs. 

### Expected behavior
The stale message should be logged once for its corresponding resource.

**Comment by narendly** [comment]
Is this related to either https://github.com/apache/helix/issues/1938 or https://github.com/apache/helix/issues/1802?

**Comment by NealSun96** [comment]
@narendly Not a duplicate issue, but in general related, sure. It's specifically related to a single StaleMessage being logged for every resource on the instance.

**Comment by desaikomal** [comment]
can the person with  right set of access, please close this bug as we have fixed the issue and merged the change.
