### ISSUE TITLE
Error partition logging is not in effect

### ISSUE THREAD

**Issue by NealSun96** [apache/helix#1941]
### Describe the bug
Error partition logging in IntermediateStateCalcStage does not work since the if condition is always false. 

### To Reproduce
The logging is absent with error partitions. 

### Expected behavior
The logging should work correctly when there are error partitions.

**Comment by jiajunwang** [comment]
Could you please provide more information, like a code snapshot, to clarify the problem?

**Comment by NealSun96** [comment]
```
    if (!partitionsWithErrorStateReplica.isEmpty()) {
      LogUtil.logInfo(logger, _eventId,
          String.format("Partition currently has an ERROR replica in %s partitions: %s",
              resourceName, partitionsWithErrorStateReplica));
    }
```
This if condition is always false.
