### ISSUE TITLE
Upgrade ZooKeeper version to 3.5.6+

### ISSUE THREAD

**Issue by rahulrane50** [apache/helix#1971]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Upgrade ZooKeeper client version to 3.5.6+ from current 3.4.13 version

**Additional context**
To support SSL/TLS on zookeeper client side, zookeeper client version has to be 3.5.6+

**Comment by desaikomal** [comment]
may it is just me, i don't see the diffs
