### ISSUE TITLE
Race condition between instance drop and state transition message creation

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/helix#1990]
### Describe the bug
There is a potential race condition when an instance is dropped and a state transition message is created at the same time. The state transition message can recreate the `INSTANCE/<instanceId>` ZK directory, and cause instance show up in the cluster again, but without instance config.

### To Reproduce
Remove an instance from the IdealState and drop it at the same time.

### Expected behavior
The state transition message should not create the ZK directory if it does not exist.

**Comment by junkaixue** [comment]
Thanks @Jackie-Jiang. Yeah, this is an known issue that ZK set will automatically create the folder if it does not exists. We may fix it with updater for history update.
