### ISSUE TITLE
Website link to paper Untangling Cluster Management Using Helix is broken

### ISSUE THREAD

**Issue by brentwritescode** [apache/helix#2037]
### Describe the bug
The link to the paper "Untangling Cluster Management Using Helix" from SOCC Oct 2012 on https://helix.apache.org/Publications.html is broken.  It appears the entire SOCC 2012 site is no longer available (http://www.socc2012.org/home/program) and the paper has gone down with it.

Would it be possible to host a copy of the paper PDF directly on the helix.apache.org site itself?  While the paper does exist other places like ACM (https://dl.acm.org/doi/abs/10.1145/2391229.2391248), I don't think it's freely downloadable anywhere any longer.

### To Reproduce
1. Go to https://helix.apache.org/Publications.html
2. Click the "paper" link underneath "Untangling cluster management using Helix at SOCC Oct 2012"
3. Observe the "Site not found" error page

### Expected behavior
The link should point to a downloadable copy of the paper

**Comment by junkaixue** [comment]
Updated the link. Thanks!
