### ISSUE TITLE
Helix Manager - not considering the zookeeper cluster change and retrying infinitely

### ISSUE THREAD

**Issue by vaidhyanathan-ananthakrishnan-13** [apache/helix#2058]
### Describe the bug
When all the nodes in the zookeeper are modified, the zookeeper library is not smart enough to detect the changes in the zookeeper cluster itself, causing the infinite polling of the old zookeeper node to connect. 

### To Reproduce
- Start zookeeper cluster
- Add a StatechangeListerner to Helix manager 
- Change all the instances of the zookeeper cluster

Helix will try to connect to ZKNode in the zookeeper cluster,  for ExternalProviderTable update, since the host is changed, all the hosts will throw errors. 

The ZKConnection class in the Zookeeper library will keep on using the old host provider(HostProvider) and will try to connect, since all the hosts are replaced, they will keep on retrying.

### Expected behavior
The zookeeper client should be reinitialized with the updated host if there is a change in the zookeeper cluster itself. 

### Additional context
I hope The zookeeper doesn't provide this functionality out of the box, It needed to be handled separately. Attached is the run() method of the ClientCxn.java from Zookeeper. 
<img width="1691" alt="Screenshot 2022-04-23 at 12 35 50 AM" src="https://user-images.githubusercontent.com/76950121/164778390-1957e374-4c5b-4808-88b4-6cf2f1955293.png">

**Comment by narendly** [comment]
Interesting. What version of Helix were you using? We have recently upgraded the ZK version to 3.5.9, so do you want to give  that a shot if you believe ZK is the problem?

**Comment by junkaixue** [comment]
Feel free to open an new one if there is any update.
