### ISSUE TITLE
ClusterStatusMonitor is a bottleneck in BestPossibleStateCalcStage.process

### ISSUE THREAD

**Issue by richardstartin** [apache/helix#2117]
This profile was taken from an Apache Pinot controller:
<img width="1425" alt="Screenshot 2022-05-25 at 09 53 04" src="https://user-images.githubusercontent.com/16439049/170222935-5b9111b3-1373-4e71-bcc1-edf7be2db84a.png">

About 18% of the samples were in `ClusterStatusMonitor.setPerInstanceResourceStatus` (zoomed in)

<img width="1430" alt="Screenshot 2022-05-25 at 09 53 22" src="https://user-images.githubusercontent.com/16439049/170223015-611a084a-3f96-40d5-b5ec-e639886ccb68.png">

The root causes are:

* inefficient hashCode implementation in `PerInstanceResourceMonitor$BeanName`
* doing twice the work in `ClusterStatusMonitor.setPerInstanceResourceStatus` because `containsKey` is called before `get`, when the same effect could be achieved efficiently by `computeIfAbsent`

**Comment by desaikomal** [comment]
Richard, great finds. If you don't mind asking me, what profiling tool are you using?

**Comment by richardstartin** [comment]
> Richard, great finds. If you don't mind asking me, what profiling tool are you using?

I'm using JFR, visualised with JMC
