### ISSUE TITLE
Unnecessary calls to `String.format` in `LogUtil`

### ISSUE THREAD

**Issue by richardstartin** [apache/helix#2119]
It isn't necessary to call `String.format` when using Log4j - it has more efficient means of performing string interpolation.
<img width="581" alt="Screenshot 2022-05-25 at 10 36 54" src="https://user-images.githubusercontent.com/16439049/170231905-047851af-d900-4a47-b41e-cd3759c5e9c0.png">

This leads to unnecessary overhead.

**Comment by junkaixue** [comment]
Thanks for sharing findings!
