### ISSUE TITLE
Targeted TaskConfigMaps are never communicated to Task.

### ISSUE THREAD

**Issue by manishrawat1992** [apache/helix#2172]
### Describe the bug
When I add configMap to Targeted Task. It is not communicated in the Task executionContext

### To Reproduce
Create a targeted task with a custom configMap. Task is not invoked with that config.

```JobConfig.Builder jobBuilder = new JobConfig.Builder();
        jobBuilder.setTaskRetryDelay(0);
        jobBuilder.setMaxAttemptsPerTask(10);
        jobBuilder.setNumConcurrentTasksPerInstance(100);
        jobBuilder.setRebalanceRunningTask(false);
        jobBuilder.setTargetResource(resourceName);
        jobBuilder.setTargetPartitionStates(Sets.newHashSet(LeaderOfflineSMD.States.LEADER.name()));

        List<TaskConfig> taskCfgs = Lists.newArrayList();

        for(int i = 0; i < num_partitions; i++) {
            String target = getPartitionName(resourceName, i);
            TaskConfig taskCfg = new TaskConfig.Builder()
                    .addConfig("configs", jobConfig)
                    .setCommand("OplogCopy")
                    .setTaskId(String.valueOf(i))
                    .setTargetPartition(target)
                    .build();

            taskCfgs.add(taskCfg);
        }
        jobBuilder.addTaskConfigs(taskCfgs);
```
### Expected behavior
The configMap is successfully communicated to Task

### Additional context
This is because during building JobConfig class using Builder, the field variable _targetedTaskConfigMap is never populated.
This is required in Workflow.java in function addJob() which calls getTaskConfigMap() in JobConfig, returning empty map from _targetedTaskConfigMap.

**Comment by junkaixue** [comment]
ConfigMap will not work with targeted resource. Because when you build a job for a targeted resource. It means each of the partition will run the same task for this job. 

So even you specific the config map, it will be ignored. This is expected behavior. If you would like to use config map, please do not make it as targeted job.
