### ISSUE TITLE
admin-webapp throws NullPointerException for every request

### ISSUE THREAD

**Issue by wmorgan6796** [apache/helix#2185]
### Describe the bug
Every API call the admin-webapp throws a NullPointerException. It's due to the fact that mapper [here](https://github.com/apache/helix/blob/master/helix-admin-webapp/src/main/java/org/apache/helix/webapp/resources/ResourceUtil.java#L50) is used in the line above it. Since Java's initialization of static members follows the order in which they're declared, the mapper hasn't been instantiated yet, causing the NullPointerException [here](https://github.com/apache/helix/blob/11846ccbfe30820a4403b90e6b115c9cdb56416a/helix-admin-webapp/src/main/java/org/apache/helix/webapp/resources/ResourceUtil.java#L111)  when line 49 of that file is evaluated.

### To Reproduce
Use any API in the admin-webapp which will return a 500 (due to the NullPointerException)

### Expected behavior
The API shouldn't return a 500 and instead return what it should.

### Additional context
Looks like this has been broken since 2020, but due to the Rest App 2.0, probably went unnoticed.

**Comment by jiajunwang** [comment]
Thanks for the contribution, @wmorgan6796

I think the plan is to deprecate admin-webapp. The fix on admin-webapp is absolutely welcomed, but I would suggest your usecase to leverage helix-rest. Or you may find more gaps forward.

**Comment by wmorgan6796** [comment]
Yeah I got confused by which one to use. I figured though the rest app 2.0 was the way to go, can't hurt to make the admin-webapp not completely broken
