### ISSUE TITLE
Unit test stability

### ISSUE THREAD

**Issue by qqu0127** [apache/helix#2257]
### Describe the bug
Right now the Helix unit test isn't stable, GitHub action https://github.com/apache/helix/actions/workflows/Helix-CI.yml has only 30% success rate in the last two months. This indicates some issues in the unit test setup.
We need to fix the unit test and have a stable signal to tell whether the code is good or not, otherwise the test becomes meaningless. 

### To Reproduce
https://github.com/apache/helix/actions/workflows/Helix-CI.yml

**Comment by desaikomal** [comment]
Quincy, i am tracking all the bugs going forward and so can we close this one, please?
