### ISSUE TITLE
HelixManagerStateListener.OnDisconnected has never been called

### ISSUE THREAD

**Issue by guomin2014** [apache/helix#2261]
### Describe the bug
I use HelixManagerFactory.getZKHelixManager(String clusterName, String instanceName,
      InstanceType type, String zkAddr, HelixManagerStateListener stateListener) to create HelixManager,Then cut off the network between the host and zookeeper,The log shows that zookeeper client is disconnected,but the HelixManagerStateListenerOnDisconnected has never been called.

### To Reproduce

1. Run worker code
```
public static void main(String[] args) {
    try {
          HelixManager helixManager = HelixManagerFactory.getZKHelixManager("clusterName", 
                "192.168.1.100_8080",  InstanceType.PARTICIPANT,  "192.168.1.200:2181", 
                new HelixManagerStateListener(){
                   @Override
	          public void onConnected(HelixManager helixManager) throws Exception {
		          System.out.println("HelixManager successfully connected");
	          }
          
	          @Override
	          public void onDisconnected(HelixManager helixManager, Throwable error) throws Exception {
		          System.out.println("HelixManager disconnected-->" + error.getMessage());
	          }
          });
          helixManager.connect();
      } catch (Exception e) {
	      e.printStackTrace();
      }
}
```

2. cut off the network between the host and zookeeper

Prevent worker(192.168.1.100) access On zk's server(192.168.1.200)
```
iptables -I INPUT -s 192.168.1.100 -j DROP
```

**Comment by jiajunwang** [comment]
The default behavior of HelixManager is trying to reconnect if the
zookeeper connection fails. It won't trigger a cleanup if you don't
explicitly call disconnect.

Best Regards,
Jiajun

**Comment by guomin2014** [comment]
> trying

During worker reconnection, The controller will monitor that the worker is disconnected, Will be rebalance,  The same partition task is performed in two workers. so Whether to associate worker reconnection with controller monitoring to avoid this situation?

**Comment by jiajunwang** [comment]
When helixmanager.disconnet is called, the existing partition on the
instance shall be transite to OFFLINE state. I remember that the Helix
participant cancels any ongoing state transition during disconnection, but
I'm not 100% sure about the detailed behavior.

On the other hand, if network disconnection happens before (or without)
HelixManager.disconnect, then from controller perspective, the participant
is gone after ZK timeout. It will rebalance and trigger state transition on
a new instance. The disconnected instance is partitioned from the rest of
the cluster. So any partitions or ongoing tasks are not visible to the
controller.
Overall, participant connectivity is the fundamental assumption in the
Helix controller, so everything regarding the participant relies on the
active ZK connection.

To avoid parallel and duplicate running tasks, one way is to add a handler
to HelixManager.Ondisconnect callback. In the handler, it is possible to
cancel the task if it has not been automatically done by the Helix
participant (as I said, I suspect auto-cancel will be triggered but I'm not
certain).

Best Regards,
Jiajun
