### ISSUE TITLE
Allow to customize the size of thread pool used by ClusterMessagingService

### ISSUE THREAD

**Issue by klsince** [apache/helix#2315]
**Is your feature request related to a problem? Please describe.**
The size of thread pool to handle state transitions is [hard coded 40](https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/messaging/DefaultMessagingService.java#L269). To be specific, there seems no way to customize the thread pool when calling registerMessageHandlerFactory() to register the message handler. This became a bottleneck when service did intensive I/O during states transitions, particularly during service startup time. 

**Describe the solution you'd like**
Please lemme know if there is already ways to customize that pool size. Otherwise, it may help to add a new [registerMessageHandlerFactory()](https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/ClusterMessagingService.java#L124) that accepts threadPoolSize to customize thread pool size.

**Additional context**
We noticed the threads handling state transitions were capped at 40, and found that this seems hard coded and no way to customize it currently. 
```
[HelixTaskExecutor-message_handle_thread_35]
```

**Comment by KKcorps** [comment]
It seems to be configurable via `HelixTaskExecutor.MAX_THREADS` option in the cluster config.
https://github.com/apache/helix/blob/master/helix-core/src/main/java/org/apache/helix/messaging/DefaultMessagingService.java#L289

**Comment by klsince** [comment]
👍
