### ISSUE TITLE
Helix metrics missing in Helix 1.0.4

### ISSUE THREAD

**Issue by qqu0127** [apache/helix#2406]
### Describe the bug
We got reached out by Uber in the public Apache Pinot Slack channel that some of the Helix metrics are missing after bumping up the Helix version from 0.9.8 to 1.0.4. Could you help identify the root cause and figure out the solution for that?

A few participant side metrics are missing, including `PendingMessages` etc

Reported in Apache Pinot https://github.com/apache/pinot/issues/10393

### To Reproduce
Steps to reproduce the behavior.

**Comment by qqu0127** [comment]
There has been a change https://github.com/apache/helix/pull/1696 that migrate static metrics to dynamic metrics.

**Comment by qqu0127** [comment]
We verified that for pinot-server running helix 1.0.4, the metrics are emitted to the mbean and JMX under Domain: CLMParticipantReport. This is also the case for a few other helix applications. An example mbean is CLMParticipantReport:ParticipantName=<instance_name>,MonitorType=ParticipantMessageMonitor

**Comment by desaikomal** [comment]
@qqu0127 - is this bug still valid? AFAIK we verified that we are doing the required. There may be additional change on the participant side may be required but there is no action on helix side.

**Comment by qqu0127** [comment]
This can be closed now as helix is emitting requiring metrics.
