### ISSUE TITLE
Hard constraint scope expansion to avoid instance overload during state transition in WAGED (N+1 scenario)

### ISSUE THREAD

**Issue by qqu0127** [apache/helix#2468]
**Is your feature request related to a problem? Please describe.**
The WAGED rebalancer assigns partitions to instance only if all the hard constraints are satisfied. However, the calculation doesn't account for the temporary state during state transition. The result is measured at the eventual state after all state transitions complete. The "N+1" scenario is when on one `instance_0`, p1 is moving out while p3 is moving in, p2 stays at instance_0. The beginning state `[p1, p2]`, and ending state `[p2, p3]` all satisfies the hard constraint, while the temporary state [p1, p2, p3] may not.

Note that this will expand the definition of hard constraint in WAGED. 

**Describe the solution you'd like**
An ideal implementation should account for the "limit" during state transition so that a set of configurable limits or constraints are always honored. 
The feature doesn't need to and should not be tied to WAGED, it should be made as a universal feature that applies to any rebalancer. (The issue is raised from WAGED applications because it's the only place such constraints are defined, but the underlying causes would apply to all)

A proposed design as in https://github.com/apache/helix/wiki/WAGED-rebalancer-Hard-Constraint-Scope-Expansion

**Comment by jiajunwang** [comment]
This is an interesting problem. Is it possible for you to write up an one-pager to elaborate your proposal? I feel we'd better not rush to coding before the high level direction is clear.

**Comment by qqu0127** [comment]
@jiajunwang Please refer to https://github.com/apache/helix/wiki/WAGED-rebalancer-Hard-Constraint-Scope-Expansion

**Comment by desaikomal** [comment]
I couldn't find a way to share Google doc from my official LinkedIn account. Here is the  write up in Google Doc: (komald@gmail.com/desaimom)

https://docs.google.com/document/d/1uxCqSU0xriUTdZIyxVoEvPMvywRgHCANatUlR0YQojk/edit#

Please note: I have added a new proposal - Approach-2. 
@jiajunwang  @NealSun96 @qqu0127 @junkaixue  - Please review and get back to us soon as there are few consumers waiting for this fix. Thanks,
komal
