### ISSUE TITLE
Helix-rest maintenanceSignal path thinks empty maintenance znode doesn't exist

### ISSUE THREAD

**Issue by GrantPSpencer** [apache/helix#2564]
### Describe the bug
When using the /maintenanceSignal path in helix-rest, if the znode does not have any data associated with it (data = null), then helix-rest will state that the cluster is not in maintenance. The /maintenance path will correctly determine that the cluster is in maintenance mode because it only checks if the znode exists and does use its data value. 

### To Reproduce
Create an empty maintenance znode under /clusterID/CONTROLLER/. 
Use /maintenance and /maintenanceSignal and observe the difference 

return is: { "error" : "Cluster MY_TEST_CLUSTER is not in maintenance mode!" }

### Expected behavior
Behavior between /maintenance and /maintenanceSginal should be the same. In this case, I think it is /maintenanceSignal that needs to be fixed to recognize empty maintenance znode's as a valid indicator that the cluster is in maintenance mode. The /maintenanceSignal can return an empty value that represents the null znode data, but it should not falsely state the cluster is not in maintenance mode.

**Comment by xyuanlu** [comment]
Fixed in PR https://github.com/apache/helix/pull/2559
