### ISSUE TITLE
Adding Multi-tenancy support to Helix

### ISSUE THREAD

**Issue by arminbalalaie** [apache/helix#2581]
**Is your feature request related to a problem? Please describe.**
Currently, to the best of my knowledge, there is no way to handle multi-tenancy using Apache Helix. By that I mean separate shard discovery for each tenant while rebalancing the resources for them as a whole. 

**Describe the solution you'd like**
You can have a separate resource for each tenant and as result a distinct way for shard discovery for that tenant. At the same time you can enable rebalancing the shards across resources to get an even distribution. This also opens up opportunities to add a load-based rebalancer as different tenants might not have similar loads (this could also be important in a single-tenant setting as shards might not be even-sized, but will be signified in a multi-tenant setting). 

Another way to address this could be through adding sub-resources and provide a way for shard discovery of sub-resources.

**Comment by junkaixue** [comment]
Thanks @arminbalalaie. I think Helix currently support tagging between instances and resources. So Apache Pinot uses this way to achieve multi-tenancy.

Also if you would like to have different instance capacity, you can check WAGED rebalance helix introduced. It is serving for different multi dimension evaluation of partition/instances for assignment.
