### ISSUE TITLE
On-demand Rebalance API

### ISSUE THREAD

**Issue by MarkGaox** [apache/helix#2594]
**Is your feature request related to a problem? Please describe.**
Helix currently incorporates a delayed rebalance feature to maintain partition assignment without alterations when a node experiences temporary downtime. This approach minimizes the partition movement until the node reconnects. However, Helix doesn't provide users with the flexibility of interrupting the delay and bootstrapping the third replica quickly. Therefore, a new Helix on-demand cluster rebalance API to force delayed offline/disabled nodes to be rebalanced shall be implemented.

**Describe the solution you'd like**
We will introduce a new cluster level config to record the time when the last on-demand rebalance API is called. It will help helix understand when to force the offline/disabled node to be rebalanced without respecting the delay window.

**Comment by jadami10** [comment]
@MarkGaox, I'm curious if this API is coming about for Pinot or some other system. I linked a Pinot issue to your PR as well

**Comment by MarkGaox** [comment]
Hi, thanks for reaching out. It hinges on whether Pinot is willing to adopt the latest version of Helix. Typically, we avoid imposing the latest version on clients and rather prioritize their willingness to opt into it.

**Comment by jadami10** [comment]
Pinot actually picked up the latest version of helix [last week](https://github.com/apache/pinot/pull/11450). But my question was more around what necessitated this feature, if you can share. Did you need on demand rebalancing for Pinot or for some other system?

**Comment by jiajunwang** [comment]
Delayed time window is configurable, I think setting up a small (or zero)
delayed time window resolves your problem?

Best Regards,
Jiajun

**Comment by MarkGaox** [comment]
Suppose that the delay window configuration is set to be 16 hours, the min active replica is 2, and the replication factor is 3. When a node is brought down for maintenance, it's still considered as holding replicas that are initially assigned to it. Consequently, the actual active replica remains 2 for subsequent 16 hours. And Espresso, one of Helix's clients, is asking for a feature that can quickly bootstrap the third replica even during the delay window. This functionality is crucial to ensure that they have sufficient cluster availability guarantee to start their cluster-wise maintenance task. 

For your 5min delay problem, [here](https://github.com/apache/helix/blob/fbefa64909781d479ec486a93d22bba416322fb8/helix-core/src/main/java/org/apache/helix/model/ClusterConfig.java#L62) is how Helix configure the delay time. Based on my understanding, Pinot should have a similar configuration. And you can probably tune it to reduce the rebalance lag.

@jadami10  Hope this answers your question.

**Comment by jadami10** [comment]
yup this answers it! https://github.com/apache/pinot/pull/11509 does just that for Pinot.
