### ISSUE TITLE
ForkJoinPool Threadpool issues in WAGED: Emergency Pipeline

### ISSUE THREAD

**Issue by himanshukandwal** [apache/helix#2596]
### Describe the bug
In WAGED: Emergency Pipeline, when checking for an active node down we are seeing internal ForkJoinPool threads getting stuck in blocking state, and FJP ending up creating a lot of worker threads.

### To Reproduce
This is very un-deterministic behavior but has happened ~3 times. 

### Expected behavior
when checking for an active node, we should not be seeing any threadpool issues.

### Additional context
N/A

**Comment by junkaixue** [comment]
@himanshukandwal is this still valid?
