### ISSUE TITLE
Helix-UI Instance Resources rows incorrectly formatted on page load

### ISSUE THREAD

**Issue by GrantPSpencer** [apache/helix#2651]
### Describe the bug
Resource view for instance does not get formatted correctly when you load it directly via the URL. 
https://<helix_ui_url>/<namespace>/<cluster>/instances/<instance_name>/resources

When you access the instance resources page directly via the url or by refreshing the page, the datatable's row widths do not seem to get properly configured and are instead set to px. This causes the row to be truncated and not correctly display the data

<img width="856" alt="Screenshot 2023-10-10 at 6 28 51 PM" src="https://github.com/apache/helix/assets/80296166/a085c2ac-8f59-446a-be12-cf2401ceb26a">

### To Reproduce
Load the instance resource view page directly via the url or by refresh. 

### Expected behavior
All data will be displayed. It works correctly when you reach that view by traversing through the UI. You can click on the "Configuration" tab and then back to "Resources" and it will then be formatted correctly.

**Comment by junkaixue** [comment]
Helix UI is deprecating. Close this.
