### ISSUE TITLE
Cross-zone Stoppable Check

### ISSUE THREAD

**Issue by MarkGaox** [apache/helix#2655]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
The current limitation of the stoppable check API restricts the evaluation of stoppable instances to a single zone, even when instances from multiple zones are provided in the given list. There's a need to extend this functionality to support cross-zone stoppable checks.

**Describe the solution you'd like**
 - [X] Refactor the existing single-zone stoppable check logic into a separate function for modularity and easier extension. #2654 
 - [X] Modify the MIN_REPLICA_CHECK to account for instances already marked for stopping, ensuring a comprehensive cross-zone evaluation.
#2680 
 - [X] Ensure the stoppable check will treat evacuating instances as to be stopped instances; build a feature that allows users to whitelist a bunch of stoppable checks.
 #2687 

**Won't do:**
 - [X] Integrate the stoppable check functionality with the helix-rest cache to minimize the load on Zookeeper reads and ensure efficient operation.

**Additional context**

**Comment by junkaixue** [comment]
Was this done?

**Comment by MarkGaox** [comment]
Thanks @junkaixue. Mark it as closed.
