### ISSUE TITLE
WAGED algorithm doc is not available 

### ISSUE THREAD

**Issue by jasperjiaguo** [apache/helix#2711]
### Describe the bug
```
/**
 * Weight-Aware Globally-Even Distribute Rebalancer.
 * @see <a
 *      href="https://github.com/apache/helix/wiki/Design-Proposal---Weight-Aware-Globally-Even-Distribute-Rebalancer">
 *      Design Document
 *      </a>
 */
```
I cannot read the doc through this link, could you please add it?

**Comment by GrantPSpencer** [comment]
Hey Jasper, thanks for catching this. This is the correct link:
https://github.com/apache/helix/wiki/Weight-Aware-Globally-Even-Distribute-Rebalancer

Opened a PR to address this issue
https://github.com/apache/helix/pull/2725

Happy New Years :)

**Comment by jasperjiaguo** [comment]
> Hey Jasper, thanks for catching this. Here is the correct link: https://github.com/apache/helix/wiki/Weight-Aware-Globally-Even-Distribute-Rebalancer
> 
> Opened a PR to address this issue #2725
> 
> Happy New Years :)

Was on vacation. Happy new year!
