### ISSUE TITLE
State transition not performed with shortest distance

### ISSUE THREAD

**Issue by Jackie-Jiang** [apache/helix#2751]
### Describe the bug
The state machine has the following state transitions:
- `CONSUMING` -> `OFFLINE`
- `OFFLINE` -> `DROPPED`
- `CONSUMING` -> `DROPPED`

When a partition of state `CONSUMING` is dropped from the ideal state, we expect one state transition `CONSUMING` -> `DROPPED` to be sent. But we observe it is performed as 2 state transitions: `CONSUMING` -> `OFFLINE` followed by `OFFLINE` -> `DROPPED`

Is this the expected behavior? Could this be a regression?

**Comment by jiajunwang** [comment]
It seems to be related to state priority or state transition priority. I
don't think Helix optimizes the cost of transition today. I vote for
enhancing this.

Best Regards,
Jiajun

**Comment by Jackie-Jiang** [comment]
@jiajunwang Thanks for the response! Is there a workaround to force Helix to do `CONSUMING` -> `DROPPED` as 1 state transition instead of 2?

**Comment by jiajunwang** [comment]
Drop and Offline states are default ones and AFAICR they have default
priority too. We can try to overwrite in SMD and see if prioritizing DROP
state and related transitions will work or not.

I will need to double check the latest code to ensure this though. Will try
to do it when I have time.

Best Regards,
Jiajun

**Comment by junkaixue** [comment]
We are in planning of building Helix 2.0.

In 2.0, Helix will not send sequential messages but the final state of the partition. All steps in the middle can be decided by users.

Some details please refer: https://github.com/apache/helix/wiki/Apache-Helix-2.0-Overview


Will close this ticket.
