### ISSUE TITLE
Add getWorkflow(long timeout) to TaskDriver

### ISSUE THREAD

**Issue by narendly** [apache/helix#326]
Sometimes ZK hangs in the getWorkflow() call, and we could provide an API with a timeout to handle this at the application level.

AC:
1. Add getWorkflow(long timeout)

**Comment by pkuwm** [comment]
I don't see the call: getWorkflow() in the source code. Did you mean [getWorkflows](https://github.com/apache/helix/blob/3e670ded2ece50e21b76fcab7fed7cb61a24eea1/helix-core/src/main/java/org/apache/helix/task/TaskDriver.java#L836)()? 
  public Map<String, WorkflowConfig> getWorkflows() 

Do you think it is alright to have a default timeout for the current call getWorkflows() and also add a new api getWorkflow(long timeout) ?

**Comment by narendly** [comment]
It is a typo - it is getWorkflows(). For now, only adding getWorkflows (timeout) would suffice.

Hunter

⁣Sent from BlueMail ​

**Comment by pkuwm** [comment]
Thanks. Are you working on it? If not, may I take this ticket and
contribute?

**Comment by narendly** [comment]
Feel free to contribute. I have not started working on it yet. The implementation should be straightforward and I could help with the review.

Hunter

⁣Sent from BlueMail ​

**Comment by pkuwm** [comment]
Awesome. I'll take it then. Thanks.

**Comment by narendly** [comment]
Won't do.
