### ISSUE TITLE
Change the way Helix triggers rebalance in purgeExpiredJobs

### ISSUE THREAD

**Issue by narendly** [apache/helix#327]
Currently, we use ResourceConfigs to trigger a rebalance. But this is causing Helix to write a ResourceConfig back to ZK, which is not desirable when a mixed-mode rebalance is happening (user may create a non-task ResourceConfig for custom preferenceLists).

AC:
1. Use an alternative way to trigger a controller rebalance.

See the code below:
`        if (expiredJobs.size() > 0) {
          // Update workflow context will be in main pipeline not here. Otherwise, it will cause
          // concurrent write issue. It is possible that jobs got purged but there is no event to
          // trigger the pipeline to clean context.
          HelixDataAccessor accessor = manager.getHelixDataAccessor();
          List<String> resourceConfigs =
              accessor.getChildNames(accessor.keyBuilder().resourceConfigs());
          if (resourceConfigs.size() > 0) {
            RebalanceScheduler.invokeRebalanceForResourceConfig(manager.getHelixDataAccessor(),
                resourceConfigs.get(0));
          } else {
            LOG.warn(
                "No resource config to trigger rebalance for clean up contexts for" + expiredJobs);
          }`

We have an alternative way to trigger a rebalance instead of having to "touch" a resource config. @lei-xia  coded this up as part his P2P messaging fix. Let's use that instead.

**Comment by dasahcc** [comment]
There is a race condition if user update the ResourceConfig at same time. Say original p1 has preference list: [1, 2, 3]. Helix read this ResourceConfig back and try to write to ZK. But at the moment the user override the p1 preference list to [4, 5, 6]. Helix will fail to update the ResourceConfig and merge it with [4, 5, 6]. So the final preference list for p1 will be [1, 2, 3, 4, 5, 6].

So anyway we should fix the issue moving away from touching ZK.
