### ISSUE TITLE
Don't log and throw: removing redundant logs right before throwing exception

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#352]
Same log message should not be logged right while an exception is also thrown. Ex.:
https://github.com/apache/helix/blob/3e670ded2ece50e21b76fcab7fed7cb61a24eea1/helix-core/src/main/java/org/apache/helix/task/TaskDriver.java#L337

The principal "don't log and throw" would be a nice practice for handling exceptions in Java. We would like to keep the logs clean and helpful without redundancy. An exception message is enough to describe the exceptional event. And the stack trace tells you in which class, method, and line the exception was thrown.

**Comment by narendly** [comment]
It makes sense not to double-log things in the log and the exception. If we want to make this change, however, let us consider the following:

1. Make sure other Helix APIs (such as REST apis) would be okay with this behavior.
2. What implications would the behavior change have on other applications built on Helix? It is important that we keep things backward compatible. If a downstream service just swallows the exception, would the information be lost? Vice versa if we removed the exception.

Hunter

⁣
