### ISSUE TITLE
Multiple problems with 0.9.0

### ISSUE THREAD

**Issue by mcvsubbu** [apache/helix#377]
We see the following issues in Pinot deployment:

1. Controller callback does not happen on a PARTICIPANT helix manager when leadership changes.
2. Other participants that host regular partitions do not get a state transition after the situation in previous step happens. The only solution is to restart the leader controller.
3. Task queues are stuck with multiple tasks in IN_PROGRESS state.

**Comment by narendly** [comment]
3 references #375.
