### ISSUE TITLE
TASK: Remove Idealstate from task framework 

### ISSUE THREAD

**Issue by alirezazamani** [apache/helix#397]
Current implementation of task framework involves utilization of ideal state which is not necessary anymore. Ideal State can be removed.

**Comment by i3wangyi** [comment]
Sounds great. It's odd to hear participants could update the IdealState on their own, during the task process. 

Why it's no longer necessary? Was the usage pattern out-dated?

**Comment by alirezazamani** [comment]
This is done. Closing the issue.
