### ISSUE TITLE
Enforce capacity key checks in the WAGED rebalancer.

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#441]
The WAGED rebalancer replies on multiple layers of config (cluster, instance, and resource) to define the capacity and quota usages. The config logic and APIs have been implemented, but we don't have the logic to check yet.

Goals:
- The rebalancer shall fail the rebalance if the configuration does not fit the expectation or contains any conflict.
- On an empty capacity/weight configuration, the rebalancer shall still be able to work.

**Comment by i3wangyi** [comment]
I suggest let's create a capacity class that takes care of everything (validation/initialization/update/), what do you think?
