### ISSUE TITLE
Propose a Trie cluster structure to replace ClusterModel/ClusterContext/OptimalAssignment, etc

### ISSUE THREAD

**Issue by i3wangyi** [apache/helix#447]
I give another thought about current Helix's problem statement and existing data models (*ClusterModel*: stores all assignable nodes and replicas, historic best assignments, *ClusterContext*: mostly tracks the metadata of cluster model) and I feel like a tree (or forest) based data structure would best describe and model the problem.  Before I dive into details or implementations of this approach, I'd like to share with you @narendly @jiajunwang and get some early feedback.

##Why tree structure?
It's actually the same concept used in Topology class implementation. The topology of {cluster -> zone -> instance -> partitions} ideally is a N-ary tree, e.g
```
class Node:
    def __init__(self, val):
         self.children = []
         self.val = val
```
or a company's orgchart. 

Given this analogy, the problem can be simply abstracted as 
**Find the best leaf nodes (partitions) assignments so that n-1 nodes (instances) is even distributed in weights**

Further, to support fast query/insert/update, a Trie data structure would be even better since it has a better performance finding the node. Why? If we've created a search query like **"/cluster/{zoneId}/{instanceId}/{PartitionId}"** a Trie could find the node in O(depth of trie) = O(1) since tree depth is fixed = 4, whereas in a simple N-ary tree one have to recursively search all its children until finding the node, time complexity is O(N).

Because Trie supports fast query, we can easily assign one replica node to an instance node in O(1) time. Vice versa, it's the same performance of reverting an assignment.
```
class Trie:
     def __init__(self, val):
         self.children = dict() # id -> next level Trie
         self.val = val
```

With the Trie definition, we can store additional properties (dynamic and static) in Trie class. For example, an instance Trie node can have properties: instance config, instance weight, id etc. A partition Trie node can have properties: partition state, weight, resource, id, etc. 
What's more interesting is we could achieve fine-grained leveled hard/soft constraints. For example, a fault zone Trie node could have a hard constraint as property: the same partitions of different states cannot be located in the same zone trie node.  
```
class ZoneTrie:
    def assign(self, node, partition):
        if (check against all zone level hard constraints passed):
               return self.children[node].assign(node, partition) # check next instance level constraint
        return False
```

One additional feature would benefit us in unit test/benchmark test is the Trie structure can be easily converted to/from a json format string
```
{ 
  "zone id<0>": {
       "instance id <50>": {
           "partition id <0>": {
              "resource": "testDB"
              "state":  "Master"
            }
        },
       "instance id <100>": {
           "partition id <1>": {
              "resource": "testDB"
              "state":  "Slave"
            }
        }
   }
}
```

It's still an early and developing idea. It takes the significant effort of doing refactor works but I believe it would be much easier to understand and maintain if one's familiar with Trie, please let me know what you think. 

Thanks!

**Comment by i3wangyi** [comment]
![cluster](https://user-images.githubusercontent.com/2618776/64213610-74034900-ce62-11e9-94b8-8dc863a35fb2.jpg)
A visual illustration of the Trie structure that aligned with Helix settings.

**Comment by jiajunwang** [comment]
Could you please review the Topology.java class? I think that one is pretty much what you are trying to design here.

To me, what you proposed is an additional layer of fault zone nodes, right?
The reason we were not using that the Topology.java at the very beginning is for simplifying the algorithm. In short, does the constraint implementation need to understand the tree structure? I don't think so.

Moreover, you won't need to replace the cluster model. Minor change the Assignable node and Topology.java would be enough. Basically you need to replace all the Nodes in the Topology.java with AssignableNode.
And you won't need to change the optimal assignment either. Because we need the result to be a flat structure. If you return a tree, the rebalancer need to translate then return it anyway.

Overall, I think this can help to clean up some code (cluster context for example). But it is not supposed to be a fundamental change. We can do this improvement anytime in the future. Eventually, whether the cluster model contains a tree or a list of nodes is transparent to the other components.


Cheers,
-Jiajun

________________________________

**Comment by i3wangyi** [comment]
> Could you please review the Topology.java class? I think that one is pretty much what you are trying to design here. To me, what you proposed is an additional layer of fault zone nodes, right? The reason we were not using that the Topology.java at the very beginning is for simplifying the algorithm. In short, does the constraint implementation need to understand the tree structure? I don't think so. Moreover, you won't need to replace the cluster model. Minor change the Assignable node and Topology.java would be enough. Basically you need to replace all the Nodes in the Topology.java with AssignableNode. And you won't need to change the optimal assignment either. Because we need the result to be a flat structure. If you return a tree, the rebalancer need to translate then return it anyway. Overall, I think this can help to clean up some code (cluster context for example). But it is not supposed to be a fundamental change. We can do this improvement anytime in the future. Eventually, whether the cluster model contains a tree or a list of nodes is transparent to the other components. Cheers, -Jiajun
> […](#)
> ________________________________ From: Yi Wang <notifications@github.com> Sent: Tuesday, September 3, 2019 3:50 PM To: apache/helix <helix@noreply.github.com> Cc: Jiajun Wang <jjwang@linkedin.com>; Mention <mention@noreply.github.com> Subject: Re: [apache/helix] Propose a Trie cluster structure to replace ClusterModel/ClusterContext/OptimalAssignment, etc (#447) [cluster]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2618776%2F64213610-74034900-ce62-11e9-94b8-8dc863a35fb2.jpg&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=%2Byxx9L2fgAzczUMJWzGoJWkU2JS%2F%2FKYuj7bt5DNsIbw%3D&reserved=0> A visual illustration of the Trie structure that aligned with Helix settings. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fhelix%2Fissues%2F447%3Femail_source%3Dnotifications%26email_token%3DAANYM2CNU7TUD5FZQZ6CUE3QH3S3LA5CNFSM4ITLSD22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5ZZX3Y%23issuecomment-527670255&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=NbwKSjq9r6Md5DtFN2pc%2FWyr4V45KWx2Cx4ytu0TfUg%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANYM2B5LMXJTAN5B2AT7YLQH3S3LANCNFSM4ITLSD2Q&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342752596&sdata=a8YP7JgG%2BHGR1ApFvrw60VaeoobYnZ7Z8fn1U6TVgtQ%3D&reserved=0>.

I've reviewed the Topology.java class and it's based on the same concept of using tree. However, modifying the exisiting one is kinda risky and touches more unnecessary places here and there. Re-writing a new one that fits the waged rebalanced job would be easier for our need.

Should constraint understand tree structure? 
Yes and No. If we go with our current design, the constraint accepts the `clustercontext` or `clustermodel` object, the constraint needs to understand and read the tree structure. 
If we define constraint and init constraint inside Trie node, e.g ZoneNode, it only needs to understand if the assignment would conflict with the zone properties; For instance node, checks if the assignment would exceed the weight of instance.

The tree doesn't conflict with the result being flat since the we could implement the data conversion to flat map inside the cluster trie node (root). As long as rebalancer holds a reference to the root node, it can easily ask for data conversion.

**Comment by i3wangyi** [comment]
> > Could you please review the Topology.java class? I think that one is pretty much what you are trying to design here. To me, what you proposed is an additional layer of fault zone nodes, right? The reason we were not using that the Topology.java at the very beginning is for simplifying the algorithm. In short, does the constraint implementation need to understand the tree structure? I don't think so. Moreover, you won't need to replace the cluster model. Minor change the Assignable node and Topology.java would be enough. Basically you need to replace all the Nodes in the Topology.java with AssignableNode. And you won't need to change the optimal assignment either. Because we need the result to be a flat structure. If you return a tree, the rebalancer need to translate then return it anyway. Overall, I think this can help to clean up some code (cluster context for example). But it is not supposed to be a fundamental change. We can do this improvement anytime in the future. Eventually, whether the cluster model contains a tree or a list of nodes is transparent to the other components. Cheers, -Jiajun
> > […](#)
> > ________________________________ From: Yi Wang [notifications@github.com](mailto:notifications@github.com) Sent: Tuesday, September 3, 2019 3:50 PM To: apache/helix [helix@noreply.github.com](mailto:helix@noreply.github.com) Cc: Jiajun Wang [jjwang@linkedin.com](mailto:jjwang@linkedin.com); Mention [mention@noreply.github.com](mailto:mention@noreply.github.com) Subject: Re: [apache/helix] Propose a Trie cluster structure to replace ClusterModel/ClusterContext/OptimalAssignment, etc (#447) [cluster]https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2618776%2F64213610-74034900-ce62-11e9-94b8-8dc863a35fb2.jpg&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=%2Byxx9L2fgAzczUMJWzGoJWkU2JS%2F%2FKYuj7bt5DNsIbw%3D&reserved=0 A visual illustration of the Trie structure that aligned with Helix settings. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHubhttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fhelix%2Fissues%2F447%3Femail_source%3Dnotifications%26email_token%3DAANYM2CNU7TUD5FZQZ6CUE3QH3S3LA5CNFSM4ITLSD22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5ZZX3Y%23issuecomment-527670255&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=NbwKSjq9r6Md5DtFN2pc%2FWyr4V45KWx2Cx4ytu0TfUg%3D&reserved=0, or mute the threadhttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANYM2B5LMXJTAN5B2AT7YLQH3S3LANCNFSM4ITLSD2Q&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342752596&sdata=a8YP7JgG%2BHGR1ApFvrw60VaeoobYnZ7Z8fn1U6TVgtQ%3D&reserved=0.
> 
> I've reviewed the Topology.java class and it's based on the same concept of using tree. However, modifying the exisiting one is kinda risky and touches more unnecessary places here and there. Re-writing a new one that fits the waged rebalanced job would be easier for our need.
> 
> Should constraint understand tree structure?
> Yes and No. If we go with our current design, the constraint accepts the `clustercontext` or `clustermodel` object, the constraint needs to understand and read the tree structure.
> If we define constraint and init constraint inside Trie node, e.g ZoneNode, it only needs to understand if the assignment would conflict with the zone properties; For instance node, checks if the assignment would exceed the weight of instance.
> 
> The tree doesn't conflict with the result being flat since the we could implement the data conversion to flat map inside the cluster trie node (root). As long as rebalancer holds a reference to the root node, it can easily ask for data conversion.



> Could you please review the Topology.java class? I think that one is pretty much what you are trying to design here. To me, what you proposed is an additional layer of fault zone nodes, right? The reason we were not using that the Topology.java at the very beginning is for simplifying the algorithm. In short, does the constraint implementation need to understand the tree structure? I don't think so. Moreover, you won't need to replace the cluster model. Minor change the Assignable node and Topology.java would be enough. Basically you need to replace all the Nodes in the Topology.java with AssignableNode. And you won't need to change the optimal assignment either. Because we need the result to be a flat structure. If you return a tree, the rebalancer need to translate then return it anyway. Overall, I think this can help to clean up some code (cluster context for example). But it is not supposed to be a fundamental change. We can do this improvement anytime in the future. Eventually, whether the cluster model contains a tree or a list of nodes is transparent to the other components. Cheers, -Jiajun
> […](#)
> ________________________________ From: Yi Wang <notifications@github.com> Sent: Tuesday, September 3, 2019 3:50 PM To: apache/helix <helix@noreply.github.com> Cc: Jiajun Wang <jjwang@linkedin.com>; Mention <mention@noreply.github.com> Subject: Re: [apache/helix] Propose a Trie cluster structure to replace ClusterModel/ClusterContext/OptimalAssignment, etc (#447) [cluster]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2618776%2F64213610-74034900-ce62-11e9-94b8-8dc863a35fb2.jpg&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=%2Byxx9L2fgAzczUMJWzGoJWkU2JS%2F%2FKYuj7bt5DNsIbw%3D&reserved=0> A visual illustration of the Trie structure that aligned with Helix settings. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fhelix%2Fissues%2F447%3Femail_source%3Dnotifications%26email_token%3DAANYM2CNU7TUD5FZQZ6CUE3QH3S3LA5CNFSM4ITLSD22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5ZZX3Y%23issuecomment-527670255&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=NbwKSjq9r6Md5DtFN2pc%2FWyr4V45KWx2Cx4ytu0TfUg%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANYM2B5LMXJTAN5B2AT7YLQH3S3LANCNFSM4ITLSD2Q&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342752596&sdata=a8YP7JgG%2BHGR1ApFvrw60VaeoobYnZ7Z8fn1U6TVgtQ%3D&reserved=0>.



> Could you please review the Topology.java class? I think that one is pretty much what you are trying to design here. To me, what you proposed is an additional layer of fault zone nodes, right? The reason we were not using that the Topology.java at the very beginning is for simplifying the algorithm. In short, does the constraint implementation need to understand the tree structure? I don't think so. Moreover, you won't need to replace the cluster model. Minor change the Assignable node and Topology.java would be enough. Basically you need to replace all the Nodes in the Topology.java with AssignableNode. And you won't need to change the optimal assignment either. Because we need the result to be a flat structure. If you return a tree, the rebalancer need to translate then return it anyway. Overall, I think this can help to clean up some code (cluster context for example). But it is not supposed to be a fundamental change. We can do this improvement anytime in the future. Eventually, whether the cluster model contains a tree or a list of nodes is transparent to the other components. Cheers, -Jiajun
> […](#)
> ________________________________ From: Yi Wang <notifications@github.com> Sent: Tuesday, September 3, 2019 3:50 PM To: apache/helix <helix@noreply.github.com> Cc: Jiajun Wang <jjwang@linkedin.com>; Mention <mention@noreply.github.com> Subject: Re: [apache/helix] Propose a Trie cluster structure to replace ClusterModel/ClusterContext/OptimalAssignment, etc (#447) [cluster]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F2618776%2F64213610-74034900-ce62-11e9-94b8-8dc863a35fb2.jpg&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=%2Byxx9L2fgAzczUMJWzGoJWkU2JS%2F%2FKYuj7bt5DNsIbw%3D&reserved=0> A visual illustration of the Trie structure that aligned with Helix settings. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fapache%2Fhelix%2Fissues%2F447%3Femail_source%3Dnotifications%26email_token%3DAANYM2CNU7TUD5FZQZ6CUE3QH3S3LA5CNFSM4ITLSD22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5ZZX3Y%23issuecomment-527670255&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342742599&sdata=NbwKSjq9r6Md5DtFN2pc%2FWyr4V45KWx2Cx4ytu0TfUg%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAANYM2B5LMXJTAN5B2AT7YLQH3S3LANCNFSM4ITLSD2Q&data=02%7C01%7Cjjwang%40linkedin.com%7Cad9e6d2425084bc563f708d730c120d7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637031478342752596&sdata=a8YP7JgG%2BHGR1ApFvrw60VaeoobYnZ7Z8fn1U6TVgtQ%3D&reserved=0>.

**Comment by narendly** [comment]
Interesting idea, but I think that at this stage, we could first get the overall functionality of the rebalancer up and running. Like @jiajunwang said, since we are trying to tread the path of least resistance (change), I think we could revisit this in the future for optimizations that could be worked into this thing.

Cool diagram though!! :)

**Comment by i3wangyi** [comment]
@jiajunwang @narendly 
I understand the timeline constraint, the new data structure is not something we need to do right now. I'd just like to propose the idea and have everyone on the same page, think about the pros/cons of the new design, add/update the design when it makes sense, etc.
If I have some bandwidth, I could draft a PR of interfaces and dummy implementations only so you guys have a better idea and discuss further base on that.
