### ISSUE TITLE
Move Zookeeper Access Layer into separate module

### ISSUE THREAD

**Issue by kaisun2000** [apache/helix#556]
First step in horizontally scaling Zookeeper in Helix. Consolidate the Zookeeper accessing code into a separate module, helix-zk. 

The intended class and interfaces to be moved are the following:
HelixZkClient
HelixZkClientFactory 
DedicatedZkClientFactory
SharedZkClientFactory
ZkConnectionManager

zookeeper/ZkClient
zookeeper/ZkConnection
zookeeper/ZkEventThread

PathBasedZkSerializer
BasicZkSerializer
ChainedPathZkSerializer
PreFetch
ZkAsyncCallbacks
ZkClient

The goal is to make it backward compatible. Namely users of the helix-core would not need to change code that they would still be able to compile the code and maintain the same behavior

**Comment by narendly** [comment]
Do we still want to call it "helix-zk"? I thought the idea was to have a module fully decoupled from Helix's logic. In that case, names like "zookeeper-core" or "zk-api" might be more appropriate?

@lei-xia

**Comment by kaisun2000** [comment]
Will share the diff soon. Feel free to comment on the naming there.
