### ISSUE TITLE
AssignmentMetadataStore should skip updating if the new version is identical to the old one

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#562]
Currently, our AssignmentMetadataStore always update to ZK on any new version of assignment data. This is not necessary and increases ZK traffic.
We should compare the new version with the in-memory cache and avoid write if updating is not necessary.

**Comment by jiajunwang** [comment]
@narendly Could you please help with this issue? Thanks.

**Comment by narendly** [comment]
Ack.
