### ISSUE TITLE
Context is initialized when IdealState is existed but config is missing

### ISSUE THREAD

**Issue by alirezazamani** [apache/helix#582]
In WorkflowDispatcher.java there is a function called getOrInitializeWorkflowContext that creates the context without checking the config. In this case, if workflow is expired and IdealState is still existed in cache or ZooKeeper, getOrInitializeWorkflowContext creates a new context which is not desirable.

**Comment by narendly** [comment]
Could we spell out IS (IdealState)?

**Comment by alirezazamani** [comment]
> Could we spell out IS (IdealState)?

Done.
