### ISSUE TITLE
OnlineOffline model only works up to 0.6.9

### ISSUE THREAD

**Issue by esarkissian-rythmos** [apache/helix#609]
We have been working with Helix for some time now, and we observed that in any version higher than 0.6.9, when using the simple OnlineOffline model, we observe the following:

- Partitions 100
- Single resource - e.g. buffer.queue
- Replicas: 1

Using the cli tools in the Helix distro, we saw that the cluster has the following issues:

- More than one participant receives ONLINE for the same partition before completing OFFLINE.
- The cluster can't settle as we see participants fighting over the same partition, in a loop, going ONLINE/OFFLINE.

The only thing that seems to aleviate this problem (still testing), is to switch to 0.6.9. Any version above that has the above problems, it would appear.

We tested this with a 3-node ZK 3.5.6 instance, setup locally. But it happens on our AWS setups too. It just seems like in the latest versions the OnlineOffline model at leats is completely unusbale.

**Comment by kishoreg** [comment]
Can you share the controller logs?

**Comment by narendly** [comment]
Thanks for reporting. Do you think you could share with us the parameters you're using for the resource as found in the resource's IdealState?

`  NUM_PARTITIONS,
    STATE_MODEL_DEF_REF,
    STATE_MODEL_FACTORY_NAME,
    REPLICAS,
    MIN_ACTIVE_REPLICAS,
    REBALANCE_DELAY,
    @Deprecated
    DELAY_REBALANCE_DISABLED,
    @Deprecated
    IDEAL_STATE_MODE,
    REBALANCE_MODE,
    REBALANCER_CLASS_NAME,
    REBALANCE_TIMER_PERIOD,
    REBALANCE_STRATEGY,
    MAX_PARTITIONS_PER_INSTANCE,
    INSTANCE_GROUP_TAG,
    HELIX_ENABLED,
    RESOURCE_GROUP_NAME,
    RESOURCE_TYPE,
    GROUP_ROUTING_ENABLED,
    EXTERNAL_VIEW_DISABLED`

**Comment by esarkissian-rythmos** [comment]
Yes, of course. Here is the dump of the IdealState:

```json
{
  "id" : "oplog",
  "mapFields" : {
    "oplog_0" : {
    },
    "oplog_1" : {
    },
    "oplog_10" : {
    },
    "oplog_11" : {
    },
    "oplog_12" : {
    },
    "oplog_13" : {
    },
    "oplog_14" : {
    },
    "oplog_15" : {
    },
    "oplog_16" : {
    },
    "oplog_17" : {
    },
    "oplog_18" : {
    },
    "oplog_19" : {
    },
    "oplog_2" : {
    },
    "oplog_20" : {
    },
    "oplog_21" : {
    },
    "oplog_22" : {
    },
    "oplog_23" : {
    },
    "oplog_24" : {
    },
    "oplog_25" : {
    },
    "oplog_26" : {
    },
    "oplog_27" : {
    },
    "oplog_28" : {
    },
    "oplog_29" : {
    },
    "oplog_3" : {
    },
    "oplog_30" : {
    },
    "oplog_31" : {
    },
    "oplog_32" : {
    },
    "oplog_33" : {
    },
    "oplog_34" : {
    },
    "oplog_35" : {
    },
    "oplog_36" : {
    },
    "oplog_37" : {
    },
    "oplog_38" : {
    },
    "oplog_39" : {
    },
    "oplog_4" : {
    },
    "oplog_40" : {
    },
    "oplog_41" : {
    },
    "oplog_42" : {
    },
    "oplog_43" : {
    },
    "oplog_44" : {
    },
    "oplog_45" : {
    },
    "oplog_46" : {
    },
    "oplog_47" : {
    },
    "oplog_48" : {
    },
    "oplog_49" : {
    },
    "oplog_5" : {
    },
    "oplog_50" : {
    },
    "oplog_51" : {
    },
    "oplog_52" : {
    },
    "oplog_53" : {
    },
    "oplog_54" : {
    },
    "oplog_55" : {
    },
    "oplog_56" : {
    },
    "oplog_57" : {
    },
    "oplog_58" : {
    },
    "oplog_59" : {
    },
    "oplog_6" : {
    },
    "oplog_60" : {
    },
    "oplog_61" : {
    },
    "oplog_62" : {
    },
    "oplog_63" : {
    },
    "oplog_64" : {
    },
    "oplog_65" : {
    },
    "oplog_66" : {
    },
    "oplog_67" : {
    },
    "oplog_68" : {
    },
    "oplog_69" : {
    },
    "oplog_7" : {
    },
    "oplog_70" : {
    },
    "oplog_71" : {
    },
    "oplog_72" : {
    },
    "oplog_73" : {
    },
    "oplog_74" : {
    },
    "oplog_75" : {
    },
    "oplog_76" : {
    },
    "oplog_77" : {
    },
    "oplog_78" : {
    },
    "oplog_79" : {
    },
    "oplog_8" : {
    },
    "oplog_80" : {
    },
    "oplog_81" : {
    },
    "oplog_82" : {
    },
    "oplog_83" : {
    },
    "oplog_84" : {
    },
    "oplog_85" : {
    },
    "oplog_86" : {
    },
    "oplog_87" : {
    },
    "oplog_88" : {
    },
    "oplog_89" : {
    },
    "oplog_9" : {
    },
    "oplog_90" : {
    },
    "oplog_91" : {
    },
    "oplog_92" : {
    },
    "oplog_93" : {
    },
    "oplog_94" : {
    },
    "oplog_95" : {
    },
    "oplog_96" : {
    },
    "oplog_97" : {
    },
    "oplog_98" : {
    },
    "oplog_99" : {
    }
  },
  "listFields" : {
    "oplog_0" : [ ],
    "oplog_1" : [ ],
    "oplog_10" : [ ],
    "oplog_11" : [ ],
    "oplog_12" : [ ],
    "oplog_13" : [ ],
    "oplog_14" : [ ],
    "oplog_15" : [ ],
    "oplog_16" : [ ],
    "oplog_17" : [ ],
    "oplog_18" : [ ],
    "oplog_19" : [ ],
    "oplog_2" : [ ],
    "oplog_20" : [ ],
    "oplog_21" : [ ],
    "oplog_22" : [ ],
    "oplog_23" : [ ],
    "oplog_24" : [ ],
    "oplog_25" : [ ],
    "oplog_26" : [ ],
    "oplog_27" : [ ],
    "oplog_28" : [ ],
    "oplog_29" : [ ],
    "oplog_3" : [ ],
    "oplog_30" : [ ],
    "oplog_31" : [ ],
    "oplog_32" : [ ],
    "oplog_33" : [ ],
    "oplog_34" : [ ],
    "oplog_35" : [ ],
    "oplog_36" : [ ],
    "oplog_37" : [ ],
    "oplog_38" : [ ],
    "oplog_39" : [ ],
    "oplog_4" : [ ],
    "oplog_40" : [ ],
    "oplog_41" : [ ],
    "oplog_42" : [ ],
    "oplog_43" : [ ],
    "oplog_44" : [ ],
    "oplog_45" : [ ],
    "oplog_46" : [ ],
    "oplog_47" : [ ],
    "oplog_48" : [ ],
    "oplog_49" : [ ],
    "oplog_5" : [ ],
    "oplog_50" : [ ],
    "oplog_51" : [ ],
    "oplog_52" : [ ],
    "oplog_53" : [ ],
    "oplog_54" : [ ],
    "oplog_55" : [ ],
    "oplog_56" : [ ],
    "oplog_57" : [ ],
    "oplog_58" : [ ],
    "oplog_59" : [ ],
    "oplog_6" : [ ],
    "oplog_60" : [ ],
    "oplog_61" : [ ],
    "oplog_62" : [ ],
    "oplog_63" : [ ],
    "oplog_64" : [ ],
    "oplog_65" : [ ],
    "oplog_66" : [ ],
    "oplog_67" : [ ],
    "oplog_68" : [ ],
    "oplog_69" : [ ],
    "oplog_7" : [ ],
    "oplog_70" : [ ],
    "oplog_71" : [ ],
    "oplog_72" : [ ],
    "oplog_73" : [ ],
    "oplog_74" : [ ],
    "oplog_75" : [ ],
    "oplog_76" : [ ],
    "oplog_77" : [ ],
    "oplog_78" : [ ],
    "oplog_79" : [ ],
    "oplog_8" : [ ],
    "oplog_80" : [ ],
    "oplog_81" : [ ],
    "oplog_82" : [ ],
    "oplog_83" : [ ],
    "oplog_84" : [ ],
    "oplog_85" : [ ],
    "oplog_86" : [ ],
    "oplog_87" : [ ],
    "oplog_88" : [ ],
    "oplog_89" : [ ],
    "oplog_9" : [ ],
    "oplog_90" : [ ],
    "oplog_91" : [ ],
    "oplog_92" : [ ],
    "oplog_93" : [ ],
    "oplog_94" : [ ],
    "oplog_95" : [ ],
    "oplog_96" : [ ],
    "oplog_97" : [ ],
    "oplog_98" : [ ],
    "oplog_99" : [ ]
  },
  "simpleFields" : {
    "IDEAL_STATE_MODE" : "AUTO_REBALANCE",
    "MAX_PARTITIONS_PER_INSTANCE" : "50",
    "NUM_PARTITIONS" : "100",
    "REBALANCE_MODE" : "FULL_AUTO",
    "REBALANCE_STRATEGY" : "DEFAULT",
    "REPLICAS" : "1",
    "STATE_MODEL_DEF_REF" : "OnlineOffline",
    "STATE_MODEL_FACTORY_NAME" : "DEFAULT"
  }
}
```

**Comment by esarkissian-rythmos** [comment]
This could be reproduced with the cli tools:

1. Create a cluster
```bash
./helix-admin.sh --zkSvr zk:2181 --addCluster test
./helix-admin.sh --zkSvr zk:2181 --addResource test oplog 100 OnlineOffline -mode FULL_AUTO
./helix-admin.sh --zkSvr zk:2181 --addNode test localhost:12100
...
./helix-admin.sh --zkSvr zk:2181 --addNode test localhost:12104
./run-helix-controller.sh --zk:2181 --cluster test
./start-helix-participant.sh --zk:2181 --host localhost --port 12100 --cluster test
...
./start-helix-participant.sh --zk:2181 --host localhost --port 12104 --cluster test
```

Then you can also quickly kill all the nodes like this:
```bash
ps -ef | grep java | grep Example | awk '{print $2}' | xargs kill -9
```

So if you start the participants, with anything > 0.6.9, they end up in this unstable state a lot of the time.

**Comment by esarkissian-rythmos** [comment]
I should also mention that this is more likely to happen when you use a 3x ZK cluster locally. Here is the docker-compose for that setup:

```yaml
version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: stat, mntr

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: stat, mntr

  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: stat, mntr
```

**Comment by dasahcc** [comment]
@esarkissian-rythmos Do you have problem with single standalone ZK? I think most likely, it should be synchronization problems between ZK quorums. Because we test with 5 quorums ZK, OnlineOffline state model works pretty well with last Helix version.

It is hard for us to reproduce it. Or could you please share your controller log with us for debugging purpose?

**Comment by esarkissian-rythmos** [comment]
Single standalone ZK was not a problem. Only when we had the 3x deployment of ZK we saw these issues. But why woudl a 3 node cluster of ZK have issues?

**Comment by dasahcc** [comment]
@esarkissian-rythmos I think it could related to docker of ZK. We have not try docker before. The 5 quorum ZK we deployed in VM does not have such kind of problem.

**Comment by esarkissian-rythmos** [comment]
I am travelling this week, but I can try to find some time to repro it and get the logs for the controller.

**Comment by esarkissian-rythmos** [comment]
BTW, most services these days run through docker so I would recommend testing with that.

**Comment by dasahcc** [comment]
@esarkissian-rythmos Thanks for the suggestion. Actually, we tried docker images for controllers and participants. The only leftover is quorumized ZK. Once we identify the problem, we should open a ticket for Apache Zookeeper.

**Comment by ffcai** [comment]
We were seeing same issue in our production environment. We can reproduce it in docker test environment which is similar to @esarkissian-rythmos 's config. In production, due to the application start/stop time and cluster setup, we were able to reproduce it but took a lot of time and effort. Thanks a lot to @lei-xia, we finally picked up the new rebalance strategy algo: https://helix.apache.org/0.8.4-docs/design_crushed.html. It works pretty well, we have been running it stable for several months on production. Please take a try. @lei-xia can provide more implementation details. I can also share more on our use case if you are interested.

**Comment by esarkissian-rythmos** [comment]
Thanks for the note @ffcai - we have pretty much stayed on the old version which has been running really stable in Prod. Is this crushed algorithm a recent development?

**Comment by ffcai** [comment]
It's introduced in `0.8.4`. In our production, we upgraded to `0.8.4` last year and stayed on it since then. We also have another use case running old version `0.6.x` for years, but uses different rebalance strategy, no issues, stable.

**Comment by dasahcc** [comment]
Thanks for sharing the info @ffcai and @esarkissian-rythmos. Do you have detailed logs for ZK? Better to be transaction log for that. Then we can know whether that's ZK sync up issue or something else.

**Comment by junkaixue** [comment]
Feel free to reopen this ticket if you have any update.
