### ISSUE TITLE
Controller leader switch may trigger some additional (unexpected) rebalance in the WAGED rebalancer

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#660]
1. Since the WAGED rebalancer determines the rebalance scope by comparing in-memory cluster data cache, it is possible that a controller leader switch impacts this scope calculating. Then the scope could be enlarged or shrank.
2. In addition, if the leader switch happened while a rebalance pipeline is proceeding, we might see 2 versions output of the best possible state from the different controller (need to confirm if the pipeline would continue once the leadership switch happens. If that's the case, some partitions might be moved back and forth.

To solve this,
1. Considering reset the data change detector on new session handling.
2. We need to confirm that a rebalance pipeline will be stopped once the leadership of the controller has been switched.

**Comment by jiajunwang** [comment]
As an initial investigation, this case will only impact the baseline calculation. Since the partial rebalance won't take the change detector state as an input. Then since the baseline is not directly used to generate the IdealStates, it might be OK that even the baseline is changed slightly after leadership switch. We would keep this issue open and test this case.

**Comment by i3wangyi** [comment]
Just see this ticket, actually, it can be a pretty big change. Not sure about #1 that we need to modify the new session handling for waged rebalancer, if there's another option existence, I will be against the idea of handling session to fit one specific rebalance algorithm;

#2, cannot we just let the pipeline continue to finish BUT when it tries to write to ZK, you could check if the leader is still the leader of the cluster and let it fail if not

**Comment by jiajunwang** [comment]
@i3wangyi I agree with you. Let's figure out a generic way instead of just fix it for the WAGED rebalancer. Then only concern not is the baseline is potentially changed unexpectedly on leadership switch. I'm not sure about the impact. Do you think we can stress test it?

**Comment by i3wangyi** [comment]
To simulate mastership hand-off in CHO can be pretty tricky, I would say it's possible but requires some clever designs (maybe manually create messages to the controller_participants).

**Comment by jiajunwang** [comment]
What's in my mind, find out the super cluster resource for the tested cluster. Then disable this resource partition in the current leader. And the leadership will be moved to another controller. Then we can remove/adding that disabled partition from the resource config again and again. This will trigger frequent leadership switch.

**Comment by jiajunwang** [comment]
Just to record an idea from @narendly.
1. reset the change detector on leadership acquired.
2. if the change detector has no previous status recorded, trigger partial rebalance only. Then schedule a full baseline calculation after to catch up if any newly added resources are not assigned.

Some more details to think about. But I think it's a good idea.
We will consider this fix together with the testing result.

**Comment by jiajunwang** [comment]
I tried some options. The step one mentioned before is doable. But step two is concerning because of one case. If a new instance joining the cluster at the moment of a leadership switch, we might end up assign nothing to it since the baseline will only assign newly added resources. So before we confirm if there is any real problem, let's just keep the original design that the leadership switch will cause the rebalancer to re-evaluate all partitions assignment.

**Comment by narendly** [comment]
@jiajunwang Let's be clear about terminology.

Controller leader switch might cause additional/unexpected **rebalance** or **movement**? I think from the context, what you meant was movement since resetting the change detector would certainly trigger another rebalance (since resetting it would create a big delta).

Could you confirm that this understanding is correct? @jiajunwang
