### ISSUE TITLE
TestZKUtil is not stable due to the dependency between test methods.

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#689]
The test verifies the expected node count. However, since every test method creates some znodes without removing them, if the methods are executed in a different order as they are listed in the file, the result might be a failure.

**Comment by mgao0** [comment]
@jiajunwang

**Comment by jiajunwang** [comment]
@mgao0 Thanks.

**Comment by jiajunwang** [comment]
@mgao0, please confirm if this issue has been fixed and close if no more work required.

**Comment by mgao0** [comment]
@jiajunwang This issue has been fixed. I don't own this issue so could not close it. Could you help me close the issue please? Thank you!
