### ISSUE TITLE
NoClassDefFoundError for WAGED rebalancer

### ISSUE THREAD

**Issue by jiajunwang** [apache/helix#707]
The root cause is that we skip the check for the WAGED rebalanced resource when maintenance mode is enabled. This causes an unexpected error print out.
We should fix the validation logic and the error message will be gone. This won't impact the correctness of pipeline logic.

**Comment by jiajunwang** [comment]
IllegalName: org/apache/helix/controller/rebalancer/waged/WagedRebalancer
java.lang.ClassLoader.preDefineClass - Line 654 (ClassLoader.java)
java.lang.ClassLoader.defineClass - Line 761 (ClassLoader.java)
java.security.SecureClassLoader.defineClass - Line 142 (SecureClassLoader.java)
java.net.URLClassLoader.defineClass - Line 467 (URLClassLoader.java)
java.net.URLClassLoader.access$100 - Line 73 (URLClassLoader.java)
java.net.URLClassLoader$1.run - Line 368 (URLClassLoader.java)
java.net.URLClassLoader$1.run - Line 362 (URLClassLoader.java)
java.security.AccessController.doPrivileged - Line -2 (AccessController.java)
java.net.URLClassLoader.findClass - Line 361 (URLClassLoader.java)
org.eclipse.jetty.webapp.WebAppClassLoader.foundClass - Line 649 (WebAppClassLoader.java)
org.eclipse.jetty.webapp.WebAppClassLoader.loadClass - Line 555 (WebAppClassLoader.java)
java.lang.ClassLoader.loadClass - Line 357 (ClassLoader.java)
org.apache.helix.util.HelixUtil.loadClass - Line 133 (HelixUtil.java)
org.apache.helix.controller.stages.BestPossibleStateCalcStage.getCustomizedRebalancer - Line 424 (BestPossibleStateCalcStage.java)
org.apache.helix.controller.stages.BestPossibleStateCalcStage.getRebalancer - Line 442 (BestPossibleStateCalcStage.java)
org.apache.helix.controller.stages.BestPossibleStateCalcStage.computeSingleResourceBestPossibleState - Line 342 (BestPossibleStateCalcStage.java)
org.apache.helix.controller.stages.BestPossibleStateCalcStage.compute - Line 140 (BestPossibleStateCalcStage.java)
org.apache.helix.controller.stages.BestPossibleStateCalcStage.process - Line 85 (BestPossibleStateCalcStage.java)
org.apache.helix.controller.pipeline.Pipeline.handle - Line 68 (Pipeline.java)
org.apache.helix.controller.GenericHelixController.handleEvent - Line 728 (GenericHelixController.java)
org.apache.helix.controller.GenericHelixController.access$500 - Line 120 (GenericHelixController.java)
org.apache.helix.controller.GenericHelixController$ClusterEventProcessor.run - Line 1266 (GenericHelixController.java)

**Comment by jiajunwang** [comment]
The root cause is job resource rebalance fetching logic.

>     case TASK:
>       rebalancer = getCustomizedRebalancer(idealState.getRebalancerClassName(), resourceName);
>       break;

It should be a potential problem in the test only. Since in prod environment,  the job resources will never be configured with a Waged rebalancer.

**Comment by lei-xia** [comment]
Just curious, why a Job resource even being configured to use Waged rebalancer?

**Comment by jiajunwang** [comment]
It's a problematic test script. Not quite possible in a product. But the error message is a real bug though.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jiajunwang** [comment]
I took a closer look. Might not be related to the job resources. Let me try if I can reproduce the issue.

**Comment by jiajunwang** [comment]
It is most likely to be a lib version mismatch. As I checked the code, if there is any logic error, the class should be able to initialize the same, and we will get a casting failure instead of class not found.
Close this issue since it is only seen in the tests with the new build (and mixed lib version probably).
