### ISSUE TITLE
Huge CPU spike after upgrading from 0.8.2 to 0.8.4 (0.8.3)

### ISSUE THREAD

**Issue by nikhilvavs** [apache/helix#748]
We were using apache helix 0.8.2 and upgraded to using 0.8.4.
After upgrading, we saw a huge spike in the CPU usage where it jumped from around 80% to 180% with the newer library.
![image](https://user-images.githubusercontent.com/5173634/74261999-154fce80-4d22-11ea-95e6-c04646b9f909.png)

On profiling the service, we saw that the upgraded version was spending a lot more time in helix code.
And caused by introducing a synchronized block in [this commit](https://github.com/apache/helix/commit/8c8f79c5e545818c0e4478addea453fc42b6d003)

Is there thing we can do to improve performance?

**Comment by jiajunwang** [comment]
@nikhilvavs Thanks for reporting the issue. We will take a look at this. Could you please share more about your profiling? What makes you think it is related to the synchronized block?

**Comment by nikhilvavs** [comment]
We took flame graphs of the CPU with and without the upgraded version. 
The upgraded version had 25.7% samples from `org/apache/helix/common/DedupEventProcessor.run` compared to 3.23% in the normal revision.

**Flame graph from 0.8.2:**
Although not very clear from this image, the small box next to `java/lang/Thread.run` (second row from bottom) is the box corresponding to helix code 
![image](https://user-images.githubusercontent.com/5173634/74310773-f0943f00-4d93-11ea-9fe3-8c238feb340b.png)


**Flame graph from the upgraded version (0.8.4):** 
You can see a significant increase in the number of samples in `DedupEventProcessor.run`
![image](https://user-images.githubusercontent.com/5173634/74310380-1b31c800-4d93-11ea-9b3d-b72c8f27f9c6.png)


**Flame graph zoomed in on details with helix (version 0.8.4):**
![image](https://user-images.githubusercontent.com/5173634/74310985-70baa480-4d94-11ea-9e94-0f6b8c895d80.png)

Apologies for not being able to attach the complete svg.

We checked the commits in `DedupEventProcessor.java` and saw that the commit was introduced in 0.8.3. (It may have been some other function inside as well.)

**Comment by nikhilvavs** [comment]
I tested once again and found that this started in 0.8.3. 
The flame graph showed that it was taking a lot of time in the deserializer, but I don't see any major changes that can cause this b/w 0.8.2 and 0.8.3 - [Diff](https://github.com/apache/helix/compare/helix-0.8.2...helix-0.8.3?diff=unified)
I would be happy to help debug this further, but if you can give me some steps that I can take.

**Comment by junkaixue** [comment]
We optimized it for the serialize part. This will be duplicate ticket.
