### ISSUE TITLE
Remove deprecated classes/methods in RealmAwareZkClient

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#783]
- We have `I0ItecIZkStateListnerImpl` in `RealmAwareZkClient`. But `RealmAwareZkClient` is a new interface, we don't want `I0ItecIZkStateListnerImpl` any more in this new interface.

https://github.com/apache/helix/blob/8c050b3928af3e4076311744076dcc75cc21e602/zookeeper-api/src/main/java/org/apache/helix/zookeeper/api/client/RealmAwareZkClient.java#L271

- deprecated.IZkStateListener should also be removed in this new interface.
```
@Deprecated
void subscribeStateChanges(
      final org.apache.helix.zookeeper.zkclient.deprecated.IZkStateListener listener);
```

**Comment by narendly** [comment]
Thanks for tracking this item!
