### ISSUE TITLE
Test newly instrumented Helix Java APIs

### ISSUE THREAD

**Issue by narendly** [apache/helix#891]
We need a comprehensive integration test that tests the realm-aware functionalities of new Helix Java APIs and fix any bugs.

**Comment by jiajunwang** [comment]
Question, I assume we have the unit test coverage already. How to distinguish the integration test from the unit test? Any guideline? This is more of a common question to all components. But I think it would be a good start point to do it for the new realm-aware functionalities.

**Comment by narendly** [comment]
Integration tests involve multiple self-serving components such as ZK, Metadata Store Directory Service, a Controller instance, Mock Participant instances, etc.

Unit tests just test the logic of methods.
