### ISSUE TITLE
Move ZK related tests from helix-core to zookeeper-api

### ISSUE THREAD

**Issue by huizhilu** [apache/helix#971]
A new module zookeeper-api is created. But zk related tests are still in helix-core. If we would like to add a new test to an existing ZK test class in helix-core, we have to run all tests in helix-core and zookeeper-api. Our goal is we can run only tests in zookeeper-api. 

Current reason why we don't move tests from helix-core to zookeeper-api is, some tests are mixed for helix-core and ZK and there are circular dependencies. It would benefit developers and make the structure clear if we can move ZK related tests to zookeeper-api.

**Comment by narendly** [comment]
Let's also consider moving ZkTestHelper to zookeeper-api. We might want to make this available to users so that they could use it to write their integration tests.
