### ISSUE TITLE
Zk connection is closed when one shared zkclient calls close()

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#987]
Current logic in shared Zkclient is if close() is called, the shared zk connection is also closed. This brings a disconnection problem for the other shared Zkclients that are still also using the shared zk connection. And these unclosed shared zkclients are not able to connect to zk.

Are we expecting the behavior for shared zkclient? Can we improve it to close the connection only if all the shared zkclients using this zk connection are closed?

If we would like to improve it like this, we can add a counter for the one zk connection. Only if the counter is reduced to 0, we close this zk connection.

**Comment by jiajunwang** [comment]
I believe what you mentioned as the expected behavior is the current design.

**Comment by pkuwm** [comment]
@jiajunwang Thanks JJ for the info. Double checked the code. The design is correct: shared zkclient calling `close()` doesn't close the zk connection. The connection manager closes the connection. And it works as expected.

Closing this issue.
